<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Decline</name>
   <tag></tag>
   <elementGuidId>ddc94300-919f-4ea6-8b83-3bd487a1f23c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#decline_cookies_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='decline_cookies_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>15ec6416-bd14-4213-b973-1daca9e8598e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>decline_cookies_button</value>
      <webElementGuid>01ca4343-5cc9-49eb-abd7-574c51886596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uxa-log</name>
      <type>Main</type>
      <value>privacy_consent_banner_decline_all_button</value>
      <webElementGuid>37ad19d4-2aca-4542-9c32-4bbf8c290a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hKFyIo bdDYJz</value>
      <webElementGuid>0ff69e47-52e4-47af-943b-4c77b41ef0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Decline</value>
      <webElementGuid>e47ad317-7161-4cf2-bb16-7a7a3cf60915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;decline_cookies_button&quot;)</value>
      <webElementGuid>3bf92caa-a716-431d-8b09-e60c51e556e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dropbox - API Request Authorization - Sign in/iframeccpa-iframe</value>
      <webElementGuid>1503811a-6749-46d1-ba78-8b6ba1d8023b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='decline_cookies_button']</value>
      <webElementGuid>9ddfe94b-32cc-44ce-8ca5-d77966750310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ccpa_consent_banner']/button</value>
      <webElementGuid>be24c51c-6ada-4871-b646-ec3836ec24a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Consent Tool'])[1]/following::button[1]</value>
      <webElementGuid>29446883-0e7f-4133-9501-487a196225b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy FAQs'])[1]/following::button[2]</value>
      <webElementGuid>06e10272-ba49-4430-8eab-ccfb6c88d880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accept All'])[1]/preceding::button[1]</value>
      <webElementGuid>a7e20c0e-2a54-45bd-930f-73544c6febd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Decline']/parent::*</value>
      <webElementGuid>fdab8463-0e1d-4a1b-9f0d-c1740dfaa33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>213e2f37-8cce-48b7-a350-c996b95a52db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'decline_cookies_button' and (text() = 'Decline' or . = 'Decline')]</value>
      <webElementGuid>eeacfd6b-acdf-4ad7-bafc-41db3af65254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
