<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframeccpa-iframe</name>
   <tag></tag>
   <elementGuidId>5122101a-9326-4c56-ad2a-6b81df64fba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ccpa-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ccpa-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b08ecfd0-611b-4cb7-9cdb-26a5080e2c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.dropbox.com/ccpa_iframe?hide_gdpr=false&amp;is_migration_gate_enabled=true&amp;should_disable_banner=false&amp;parent_domain_consent_cookie=null&amp;should_auto_open_options=false&amp;locale_override=en&amp;gpc_signal=undefined</value>
      <webElementGuid>0549d1ae-c3b7-45e7-a978-8216b840d112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ccpa-iframe</value>
      <webElementGuid>eaa078f7-0291-4b5d-b733-714267b86028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6ecadd47-57f3-493a-9eb5-1f12f239419a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>bcf02556-b45e-4dc5-9407-a0bb090f2264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccpa-iframe&quot;)</value>
      <webElementGuid>729e6495-2eb5-48a2-8c57-9c39d7276baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dropbox - API Request Authorization - Sign in/iframe_Log in or sign up to Dropbox to link_604bec</value>
      <webElementGuid>d0ae35cb-10c0-400b-8f5a-343ca26a697a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ccpa-iframe']</value>
      <webElementGuid>33a27fc3-7693-4daf-8504-f5c49f4fbaff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cb6e6bf5-073d-44c4-bbec-17b96098d1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://www.dropbox.com/ccpa_iframe?hide_gdpr=false&amp;is_migration_gate_enabled=true&amp;should_disable_banner=false&amp;parent_domain_consent_cookie=null&amp;should_auto_open_options=false&amp;locale_override=en&amp;gpc_signal=undefined' and @id = 'ccpa-iframe']</value>
      <webElementGuid>c9591868-e909-43a5-a50a-1f2cb3d01a0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
