<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Log in or sign up to Dropbox to link_604bec</name>
   <tag></tag>
   <elementGuidId>35c06aa6-f58a-4816-b2cd-4730ffbaa3b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#consent-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='consent-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8300e978-9272-48d4-bbf1-d7963fa53924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://consent.dropbox.com?hide_gdpr=false&amp;is_ccpa_enabled=true&amp;is_migration_gate_enabled=true&amp;should_disable_banner=false&amp;gpc_signal=undefined&amp;origin=https%253A%252F%252Fwww.dropbox.com&amp;sandbox_redirect=false&amp;locale=en</value>
      <webElementGuid>c29f9598-8203-4b5d-be34-faf21815b3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>strict-origin</value>
      <webElementGuid>098915e3-79b4-4af5-84ef-54ba005b8ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-scripts allow-same-origin allow-popups allow-forms</value>
      <webElementGuid>d2fe5165-d2b1-488d-b873-82633515cf9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_consent-iframe_1x1n8_1 _ccpa-banner-visible_1x1n8_15</value>
      <webElementGuid>7fb8715d-6f26-4dd5-b80e-d33a2d4408cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>consent-iframe</value>
      <webElementGuid>f51b0dc1-48f0-4b48-be5e-11a57a2e682a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cf55c2bd-b526-4195-8ae8-36f6141b1369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d58094e9-3789-4360-96be-534c8fe9d734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>272</value>
      <webElementGuid>128c2ce6-a63a-4747-9b87-ae0aaff0d838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>9487c257-82c3-497e-b06c-3d20c05baba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cookies &amp; CCPA Preferences - Dropbox</value>
      <webElementGuid>7d9284ab-2bd6-4e35-8abd-bfcb9b623695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0b95c654-388a-44c7-83f2-99b18f7d7b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;consent-iframe&quot;)</value>
      <webElementGuid>4c27ad4a-02df-4fec-9700-eef43b50a2b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='consent-iframe']</value>
      <webElementGuid>9b90e175-0db4-4367-9cf3-e3c4b65dfcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3d992684-96c0-4477-9078-023d4aca6a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://consent.dropbox.com?hide_gdpr=false&amp;is_ccpa_enabled=true&amp;is_migration_gate_enabled=true&amp;should_disable_banner=false&amp;gpc_signal=undefined&amp;origin=https%253A%252F%252Fwww.dropbox.com&amp;sandbox_redirect=false&amp;locale=en' and @id = 'consent-iframe' and @title = 'Cookies &amp; CCPA Preferences - Dropbox']</value>
      <webElementGuid>e8043977-4b0e-4cc9-acd3-cb02837f45c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
