<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_4Allportal Hospital Basic Flow</name>
   <tag></tag>
   <elementGuidId>690d20ea-08f0-40fa-b49c-6bb0393dc6a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='name-label-23']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name-label-23</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a8bb3240-e963-430f-9554-fadfea21401e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-label-23</value>
      <webElementGuid>cbbb3362-a220-45e7-98c3-36c01079fd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4Allportal Hospital Basic Flow</value>
      <webElementGuid>b11d450a-da0a-42e0-a045-89b2b9e926c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-label-23&quot;)</value>
      <webElementGuid>2796d635-5a9f-4f7f-a715-d77b2df68d8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='name-label-23']</value>
      <webElementGuid>7c3aef75-9d21-4c81-942a-1f784e615377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name-23']/a</value>
      <webElementGuid>14b34a88-287b-43ad-b9f9-a66f6ededde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'4Allportal Hospital Basic Flow')]</value>
      <webElementGuid>bf6e0bc8-1a61-4e46-861b-f4286a953784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v9'])[1]/following::a[1]</value>
      <webElementGuid>f0b4996d-0a18-4d1d-80fa-771557871ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v9'])[2]/preceding::a[1]</value>
      <webElementGuid>619510ef-9917-4e35-bec1-f36309ed6e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4Allportal Hospital Basic Flow']/parent::*</value>
      <webElementGuid>28ca1c99-df4c-4137-bc6a-622c54b222c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[24]/td/div/div/a</value>
      <webElementGuid>0e826707-c1d2-410b-be6d-17062b684741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'name-label-23' and (text() = '4Allportal Hospital Basic Flow' or . = '4Allportal Hospital Basic Flow')]</value>
      <webElementGuid>43916d0b-a9ed-4d9f-9ab8-4cc0858b3749</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
