<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_cyangateone_nav-link dropdown-toggle labe_63359a</name>
   <tag></tag>
   <elementGuidId>feccc324-f7a7-43ea-8451-5f5f956e055f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.dropdown-toggle.label.a-class.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cg-header']/div[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd51ebed-59b1-4db3-90b5-d7843a0fd0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link dropdown-toggle label a-class show</value>
      <webElementGuid>d0cbf57c-90fa-45fb-b56a-b8f10f2d6660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>97f096ce-40f4-4149-8b6b-73a487d6ba03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85f83051-8821-4c1c-876d-1fa865125404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f2648ab7-7250-4021-870d-00ae32b04231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cg-header&quot;)/div[@class=&quot;d-flex flex-row justify-content-center align-items-center&quot;]/ul[@class=&quot;nav&quot;]/li[@class=&quot;nav-item dropdown cursor&quot;]/a[@class=&quot;nav-link dropdown-toggle label a-class show&quot;]</value>
      <webElementGuid>de9e35c0-a0a2-4084-93a3-b524f57ac677</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cg-header']/div[2]/ul/li[3]/a</value>
      <webElementGuid>a9a7e97a-e511-4fa7-b752-8bf3e6cb05cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cyangateone'])[2]/following::a[1]</value>
      <webElementGuid>d8899796-5d10-4a08-b273-38b78c99cc74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/following::a[2]</value>
      <webElementGuid>0a5f532b-9df7-40cf-97d8-4cbb44840417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferences'])[1]/preceding::a[1]</value>
      <webElementGuid>dea2ab90-81e5-4c32-a75d-7f8f1df1162d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bgovercin@cyangate.com'])[1]/preceding::a[2]</value>
      <webElementGuid>e75044c5-d2ad-4f61-a2c1-6ab3193dc671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>5bcdf9e8-e1ef-4a7f-9c82-e48bb5752a87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
