<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dropbox Basic Flow</name>
   <tag></tag>
   <elementGuidId>f08ac7eb-682d-43b8-88dd-a71febb73d17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='name-label-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name-label-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c2176016-33f1-4104-bf83-039ea5893607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-label-1</value>
      <webElementGuid>e1fffd37-f7bd-46f3-9b98-5fa1eabd0c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dropbox Basic Flow</value>
      <webElementGuid>0acd8feb-c2f6-4884-8c5c-6ad6ea6d7f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-label-1&quot;)</value>
      <webElementGuid>c23fc9ee-8b48-45cb-83be-dfc041344fbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='name-label-1']</value>
      <webElementGuid>5baea9c7-bfc8-4ce4-82fe-bf36ad08a10d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name-1']/a</value>
      <webElementGuid>a78fd4aa-c0f0-4bbe-99db-c08da3746c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dropbox Basic Flow')]</value>
      <webElementGuid>1219a355-0109-40bf-bd4a-822cb5f63e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v50'])[1]/following::a[1]</value>
      <webElementGuid>4aa44470-0505-4c68-adef-9897d77bb443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v5'])[1]/preceding::a[1]</value>
      <webElementGuid>79068749-04d0-48bb-8fb2-41d68eae0a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dropbox Basic Flow']/parent::*</value>
      <webElementGuid>fc0c46bb-8a8d-40dc-98b4-49d5e1f5e77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/a</value>
      <webElementGuid>edc359a1-93fd-44f5-a88f-816c99e0d7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'name-label-1' and (text() = 'Dropbox Basic Flow' or . = 'Dropbox Basic Flow')]</value>
      <webElementGuid>a292894b-3b80-4621-9275-cad0b5011a35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
