<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mail basic flow</name>
   <tag></tag>
   <elementGuidId>16c96691-618d-47ea-a2ea-2ad3eb732267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-label-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='name-label-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55a0727d-6a52-42bd-9b2b-1924e11ffc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-label-0</value>
      <webElementGuid>fa7f0b93-cf8b-45b7-b835-88cb23f477b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mail basic flow</value>
      <webElementGuid>3c3d2d33-ca96-4bca-bf7c-4befef0211f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-label-0&quot;)</value>
      <webElementGuid>9e5aae9e-4228-4f76-b3f0-89e80598c31c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='name-label-0']</value>
      <webElementGuid>b4246564-98e4-4658-be95-48c7d2c942f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name-0']/a</value>
      <webElementGuid>fe7dfcdf-373f-4d4f-9216-84a0ef223396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mail basic flow')]</value>
      <webElementGuid>f3021668-5610-4cc5-811c-f244819df659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::a[1]</value>
      <webElementGuid>84f9aa00-1020-48df-a096-38416ec4c44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scheduled'])[1]/following::a[1]</value>
      <webElementGuid>5d32e382-12ec-4b93-817a-a64c474a7843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v10'])[1]/preceding::a[1]</value>
      <webElementGuid>31043406-fdb8-411e-a0a3-49910d8a7e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mail basic flow']/parent::*</value>
      <webElementGuid>95f8cb7c-931b-4be8-a4b4-0a97f3f105bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/a</value>
      <webElementGuid>659649ae-862d-4ac2-a548-719b1780f0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'name-label-0' and (text() = 'Mail basic flow' or . = 'Mail basic flow')]</value>
      <webElementGuid>97c5231d-d78c-48dc-bf6f-07bb13a20227</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
