<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mediavalet basic flow</name>
   <tag></tag>
   <elementGuidId>1401a25a-3c61-4514-ab85-a3ab45f2bfd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='name-label-24']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name-label-24</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc38534a-8178-4c42-873e-9d94f53fb77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-label-24</value>
      <webElementGuid>a1e14d01-0f75-474a-b87f-1b93daad0a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mediavalet basic flow</value>
      <webElementGuid>c66d489d-cfe5-42e0-ba0a-4cd55c68b4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-label-24&quot;)</value>
      <webElementGuid>d63bb158-0ca0-4d12-8696-45192a9a3e27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='name-label-24']</value>
      <webElementGuid>d102f206-e122-49a7-87e6-39900ee509cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name-24']/a</value>
      <webElementGuid>5a4bcdad-59e1-4a49-a573-785022df5a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mediavalet basic flow')]</value>
      <webElementGuid>d920a3f9-813f-4016-8c84-1539bc2d328d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v9'])[2]/following::a[1]</value>
      <webElementGuid>58b9be05-6e89-4c7f-b055-44599afd7c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v4'])[2]/preceding::a[1]</value>
      <webElementGuid>50d76089-2236-43eb-8caf-23e9166b2b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mediavalet basic flow']/parent::*</value>
      <webElementGuid>55477724-b369-4754-8476-45a53c75efee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td/div/div/a</value>
      <webElementGuid>a4ff14ea-80e1-4604-a331-aa9d3c05017c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'name-label-24' and (text() = 'Mediavalet basic flow' or . = 'Mediavalet basic flow')]</value>
      <webElementGuid>b0ad3816-904b-4caa-9bee-0c6976f0502e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
