<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OTMM basic flow</name>
   <tag></tag>
   <elementGuidId>4642f039-6a28-45ff-831e-dea30e483370</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='name-label-12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name-label-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22fd51ca-1caa-4e97-aea4-74669bf3e406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-label-12</value>
      <webElementGuid>a0e9a674-e617-4eca-86ad-a78bf5a132f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OTMM basic flow</value>
      <webElementGuid>69a2f815-dfdf-48a4-9599-3901df9a4e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-label-12&quot;)</value>
      <webElementGuid>ccde98da-3f08-4cd2-82e5-a7d73a01f8c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='name-label-12']</value>
      <webElementGuid>19a7f17f-493d-4a87-abf4-115a58a2eb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name-12']/a</value>
      <webElementGuid>f2c75a12-c03d-462c-93a6-9b39f80e2e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'OTMM basic flow')]</value>
      <webElementGuid>47322ae9-3a6d-4d02-8ef8-8b42ef923d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v2'])[4]/following::a[1]</value>
      <webElementGuid>72c67f8e-a01a-445e-a4e7-213093fde06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v10'])[1]/preceding::a[1]</value>
      <webElementGuid>4c27a849-2774-418d-b655-5db869fb959a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OTMM basic flow']/parent::*</value>
      <webElementGuid>5a848f9d-97bf-4f45-bf30-e5480d75f56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td/div/div/a</value>
      <webElementGuid>18e61069-1450-4ffb-9b93-1d618706b0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'name-label-12' and (text() = 'OTMM basic flow' or . = 'OTMM basic flow')]</value>
      <webElementGuid>1748ed61-5345-4415-90c8-72f3c1ae9b0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
