<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Akeneo Connoction Name</name>
   <tag></tag>
   <elementGuidId>3f0204f5-b750-4492-8168-a2fcfa06181c</elementGuidId>
   <imagePath>../../Pictures/Katalon Screenshots/Akeneo Connection Name3.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='connection-name']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>../../Pictures/Katalon Screenshots/Akeneo Connection Name3.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connection-name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'connection-name' and @type = 'text' and @placeholder = 'Connection Name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08a26edb-d2cd-4dd3-9edb-3c934f66f121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>67a471cb-67ed-44e6-b3bd-dea920543c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-name</value>
      <webElementGuid>2377df57-5382-4534-95c5-4e1088a70af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a3ccf17-1d7b-4dc2-b413-32c8052487bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3a7df8f8-4e6d-4ca7-bb64-38b904b69ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Connection Name</value>
      <webElementGuid>06cfc7b9-f84f-4a25-aa8e-9a167d90f41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-name&quot;)</value>
      <webElementGuid>4b217cec-7864-49a4-96bd-a39180c1cfa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='connection-name']</value>
      <webElementGuid>90c15abc-d03f-42c3-916b-6bcbea38464d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connection']/div/div[2]/div/div/div/input</value>
      <webElementGuid>063d7363-91bf-471b-96ef-3268aa080b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6a83127a-f389-460d-864d-8f70f2ef6790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'connection-name' and @type = 'text' and @placeholder = 'Connection Name']</value>
      <webElementGuid>6bb2f3d3-c163-44bd-ab60-63091b5082e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
