<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_COMPLETED_flow-draft-run</name>
   <tag></tag>
   <elementGuidId>848a9546-ae39-4e03-a7e9-bdba81f459dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flow-draft-run</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='flow-draft-run']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b797c9d5-6f23-4853-a85f-de337b6f711e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66779844-7e74-433e-b328-ba85b8207c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link</value>
      <webElementGuid>0588f00c-d283-4d4e-abc7-9b64b6ef8c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flow-draft-run</value>
      <webElementGuid>77c8aea8-49ec-4dd6-ba60-032c7e6ed058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c6c2a99e-2336-443a-8cec-de5b6ced4988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>el-popper-744</value>
      <webElementGuid>d5e5fb74-3141-4e49-a6e1-480fbf65076d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flow-draft-run&quot;)</value>
      <webElementGuid>3b4de08a-bea3-4c46-80c7-4d72d5757293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='flow-draft-run']</value>
      <webElementGuid>3ee7237e-31ff-4ae7-bbb7-393eafbc44c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-flow']/div/div[2]/div[2]/div/button</value>
      <webElementGuid>38489012-77f9-4632-95c1-b4deb828b5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::button[1]</value>
      <webElementGuid>e4fce321-4747-4de3-8e1e-5d3f2d77a3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'flow-draft-run', '&quot;', ')')])[1]/preceding::button[3]</value>
      <webElementGuid>81e99c0d-ec9e-40d2-8b56-50e21cda6c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Africa/Abidjan'])[1]/preceding::button[3]</value>
      <webElementGuid>9401a535-1557-4b22-aa5e-e01d136e8b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button</value>
      <webElementGuid>2cfe9b3b-2175-46f2-816b-a22c9b4c2644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'flow-draft-run']</value>
      <webElementGuid>fa93b671-e9d3-4e9d-86b1-75225a3a28b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
