<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign in</name>
   <tag></tag>
   <elementGuidId>1791f32e-886c-47bc-9f27-f8efa97d11ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.google-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-connection']/div/div[2]/div/div[3]/div[2]/div/div[2]/div/div/div/div[2]/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>90ebde32-afff-43f8-b92c-fa0d55288816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>google-button</value>
      <webElementGuid>ca81dafa-f593-4ed2-bad1-c738578c85d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>11da22cd-d8fe-4d7d-bd83-f8d7c1300112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-connection&quot;)/div[@class=&quot;card border-0 background-fb&quot;]/div[@class=&quot;card-body overflow-auto font-size-14&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;margin-top-10 d-flex flex-column&quot;]/div[1]/div[@class=&quot;d-flex flex-column margin-top-10&quot;]/div[@class=&quot;d-flex flex-column margin-top-10&quot;]/div[@class=&quot;d-flex flex-column margin-top-10&quot;]/div[1]/div[@class=&quot;d-flex flex-column margin-top-10&quot;]/div[@class=&quot;d-flex flex-column align-items-center justify-content-center&quot;]/button[@class=&quot;google-button&quot;]</value>
      <webElementGuid>905d448d-4b30-4384-821e-9a0e794b3e32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connection']/div/div[2]/div/div[3]/div[2]/div/div[2]/div/div/div/div[2]/div/button</value>
      <webElementGuid>23fea27f-17fb-4060-9b44-27eb4800cc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::button[1]</value>
      <webElementGuid>e97d2c71-3eef-47dc-a26b-11d34475b432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign in']/parent::*</value>
      <webElementGuid>d1c8446a-622e-48d6-8265-e6da187af5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/button</value>
      <webElementGuid>07198620-dfb6-4cd6-aed6-e5037ba05fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>3f5377d9-c48e-4f2d-96b9-58c6ebd0660c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
