<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Role_create-button</name>
   <tag></tag>
   <elementGuidId>eff24d92-9596-4d6c-820c-c8ef56fb91a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='create-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22bcd2b3-4c69-4901-b27c-22c30e894ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button el-button--primary el-button--mini no-border btn-oneTeg2</value>
      <webElementGuid>4a4918fc-7e1f-4771-bdde-1ec7ae530014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c0e0af1-156e-4c50-9018-c9f1bc9ff793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-button</value>
      <webElementGuid>f8deb457-36ed-4705-b161-c179aa633c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-button&quot;)</value>
      <webElementGuid>d0cb6922-16f1-44fb-8c2e-30727278bbd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='create-button']</value>
      <webElementGuid>1cd47e87-5293-4276-8581-a1c9a3af6fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='users-card']/div/div/div[2]/table/thead/tr/th[5]/div/div/div[2]/button</value>
      <webElementGuid>deccc763-f5e4-4e70-8555-e9df068fe792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/following::button[1]</value>
      <webElementGuid>128d3cc6-87f7-427d-a652-73c4259e2bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created At'])[1]/following::button[1]</value>
      <webElementGuid>823be9e3-1847-4f4a-829c-9b676af3732c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emin'])[1]/preceding::button[2]</value>
      <webElementGuid>fb1ec6f0-f9f5-45e2-92fb-0b8a6c933e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulun'])[1]/preceding::button[2]</value>
      <webElementGuid>8d120367-df37-4584-9545-71943d7b8f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>13bd393d-0ac3-4a1e-b766-362356fcb4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'create-button']</value>
      <webElementGuid>d8141592-1859-4bbc-ae68-01df1478979f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
