<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>0452db2a-2816-4b6c-89e0-f4bc4ef6db8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.el-button.el-button--default.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4e11f28-ae9d-4548-8ffc-6ba748f9b0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button el-button--default btn-primary</value>
      <webElementGuid>e2005b77-ba86-49b0-b483-da2d4a20510c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6bf0f233-7b8b-4ab9-a367-5913d5fd8ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm </value>
      <webElementGuid>d9ae9e9e-72df-45f4-a33f-d63982c7000f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/div[@id=&quot;app&quot;]/div[@class=&quot;newPassword&quot;]/div[@class=&quot;d-flex justify-content-center align-items-right flex-column&quot;]/div[@class=&quot;col-10 loginpage&quot;]/form[@class=&quot;el-form margin&quot;]/div[@class=&quot;el-form-item btn-right&quot;]/div[@class=&quot;el-form-item__content&quot;]/button[@class=&quot;el-button el-button--default btn-primary&quot;]</value>
      <webElementGuid>14bfbd86-38b1-450b-8715-333424df50ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>b2f2b5c2-b5f4-42cf-b395-37be3f168e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/form/div[5]/div/button</value>
      <webElementGuid>bed6f1b3-eff5-4c26-bf9d-a5a3f9f92f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Login'])[1]/following::button[1]</value>
      <webElementGuid>694b5e00-d550-4a9a-b3e6-67f764783590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password Matched'])[1]/following::button[1]</value>
      <webElementGuid>a0135c08-cbf0-422c-bc04-e16aaa8426d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8cbfe67c-d871-48dd-9e48-af498fb2afc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Confirm ' or . = 'Confirm ')]</value>
      <webElementGuid>9b813e94-b70a-4016-96c9-a3c04b6c9f3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
