<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Authentication_refresh-button</name>
   <tag></tag>
   <elementGuidId>213a2254-49f9-47b9-ba87-2aee5e9ad97a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refresh-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='refresh-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4325ebb-92df-4f12-8c1c-4a059657dfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button el-button--primary el-button--mini no-border btn-oneTeg margin-left-3</value>
      <webElementGuid>7b188675-b55c-4e8c-9f78-4a5f67976bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20321be0-e8ff-4ef9-9783-2cb44aa42607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refresh-button</value>
      <webElementGuid>d2a0f2b9-4091-4fd2-b54c-d36349ae94a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refresh-button&quot;)</value>
      <webElementGuid>d7f37f25-f7eb-43b7-8515-2162ecebe34d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='refresh-button']</value>
      <webElementGuid>64d8a171-06d2-4f8f-b1a2-723d03deb3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show-connections']/div/div/div/div[2]/table/thead/tr/th[5]/div/div/div[2]/button[2]</value>
      <webElementGuid>aa4d68fe-a44b-4d58-9d29-422748b0f7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authentication'])[1]/following::button[2]</value>
      <webElementGuid>f2358090-9ce4-40e8-8aa3-ed195420a0e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connector'])[1]/following::button[2]</value>
      <webElementGuid>2ccb3bb6-1e5c-4d12-8622-e9feac366de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total 0'])[1]/preceding::button[1]</value>
      <webElementGuid>f4fb42bf-ab5e-4b31-9244-f0054c432572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>0ff0fea4-2111-469d-b201-b1df53543cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'refresh-button']</value>
      <webElementGuid>2a726348-9a26-4602-b555-7cf7b960447f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
