<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dropbox Connection Katalon Test_cog-_5dcd2f</name>
   <tag></tag>
   <elementGuidId>d367c3fe-de40-4591-bcf1-4fd2a64f8163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cog-button-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cog-button-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2d54879-85ae-4316-be80-083757e72337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button el-button--primary el-button--mini no-border btn-oneTeg el-dropdown-selfdefine focusing</value>
      <webElementGuid>aea6198b-d7d0-46f2-bb1c-d899a10a3a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b7dd599-ec61-4d85-bdd4-0e32d7ffe45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cog-button-0</value>
      <webElementGuid>2b979ae3-bdc7-420f-90e2-ac8aacaf1757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>61e3f870-72a9-4c1d-ba64-75931de767c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dropdown-menu-8579</value>
      <webElementGuid>7abf126b-a32c-4c1c-a481-43f50616e7b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0683ebd6-dccb-4efe-8905-185077718105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f5ffb2f-b178-419f-9ff3-24876e432af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cog-button-0&quot;)</value>
      <webElementGuid>efa77bc3-48a6-4c73-8680-cd69b9fc61fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cog-button-0']</value>
      <webElementGuid>93e80697-3da2-41fe-87c6-c7621bf282da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show-connections']/div/div/div/div[3]/table/tbody/tr/td[5]/div/div/div/div/button</value>
      <webElementGuid>bc79a32d-132b-41ed-a088-23f0d9e9d33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropbox Connection Katalon Test'])[1]/following::button[1]</value>
      <webElementGuid>f882d61d-7feb-4068-9af4-501af334523a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authentication'])[1]/following::button[3]</value>
      <webElementGuid>a3005594-09bc-4e33-8a5c-dbebc350642f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total 1'])[1]/preceding::button[1]</value>
      <webElementGuid>9e2f0c6b-bc00-4fef-9fc4-6109463d1e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'cog-button-0', '&quot;', ')')])[1]/preceding::button[3]</value>
      <webElementGuid>393facf4-c22a-4fd3-afab-59d87b39f63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div/div/button</value>
      <webElementGuid>07d375b6-8052-4abe-98b1-8cd65c401753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'cog-button-0']</value>
      <webElementGuid>6a97a9ed-1af8-45d9-80f6-a326a26ebbe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
