<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Clear_transfer-add-left-button</name>
   <tag></tag>
   <elementGuidId>963e28c3-0e9d-4d6b-97c4-9f323ef1931a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transfer-add-left-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='transfer-add-left-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bde21385-e13f-416b-bc30-17cc677b8172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button el-button--default el-button--mini btn-oneTeg float-end mt-2 mb-2</value>
      <webElementGuid>b1043f08-0f0d-411c-9beb-ec1174a72fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a543cbc6-1445-4841-8e73-96686ce7c057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transfer-add-left-button</value>
      <webElementGuid>b728942f-e0a4-4250-91d1-fcca6bdca5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transfer-add-left-button&quot;)</value>
      <webElementGuid>baa6a958-286f-4b5b-9f53-e00accc468c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='transfer-add-left-button']</value>
      <webElementGuid>1a3aa0e2-110b-4ba9-9be5-7ee0152984d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-tenant']/div/div[2]/div/div[2]/div/div/div/div[3]/button[2]</value>
      <webElementGuid>ea7a4701-958a-4bf7-a700-20f0499717f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connectors'])[3]/following::button[2]</value>
      <webElementGuid>30b48b59-f69c-4266-8025-aa1fda28a87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenant Connectors'])[1]/preceding::button[1]</value>
      <webElementGuid>8842a9e5-33de-4117-a941-cb388ca3b166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>8949c0b6-a872-46b4-a9b8-cb044f95b9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'transfer-add-left-button']</value>
      <webElementGuid>73fca012-3a57-4569-8d5b-575feb601e93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
