<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_v1_logo-div-d5d85eaa-d857-42ca-91cb-463_1820b4</name>
   <tag></tag>
   <elementGuidId>e8cf88ca-0d07-4f28-9297-1a0a6c3b40a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='logo-div-d5d85eaa-d857-42ca-91cb-463003a6cc2d']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#logo-div-d5d85eaa-d857-42ca-91cb-463003a6cc2d</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b77be816-80d0-4426-bf16-cd0d753c0074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex flex-row</value>
      <webElementGuid>12f967b9-7df4-4ae5-beb2-66dd84055d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logo-div-d5d85eaa-d857-42ca-91cb-463003a6cc2d</value>
      <webElementGuid>150645ae-7ac9-450b-a0a5-67bf5ca6ccc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo-div-d5d85eaa-d857-42ca-91cb-463003a6cc2d&quot;)</value>
      <webElementGuid>c647a951-e465-464b-bbe6-c933f44ee1f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='logo-div-d5d85eaa-d857-42ca-91cb-463003a6cc2d']</value>
      <webElementGuid>0c805e19-97b8-447c-a7e1-fe6d96696f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flows-card']/div/div/div[3]/table/tbody/tr[2]/td[2]/div/div</value>
      <webElementGuid>d0b76d29-50b5-42fa-8396-52325e19a41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v1'])[2]/following::div[2]</value>
      <webElementGuid>810636b4-05bf-42f4-a9aa-7c5816266b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akeneo Basic Flow'])[1]/following::div[3]</value>
      <webElementGuid>e8416b35-b7eb-4d9b-8f8c-bb2617cd8142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total 2'])[1]/preceding::div[9]</value>
      <webElementGuid>a63512d4-84df-45bd-9d88-1ce3b785be6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div</value>
      <webElementGuid>ed7564f3-711b-48e9-bb84-5840bf150c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'logo-div-d5d85eaa-d857-42ca-91cb-463003a6cc2d']</value>
      <webElementGuid>f4bf743e-efd9-456b-92e5-4a774de42124</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
