<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Product Search  Retrieve v2.0  Product _602c1a</name>
   <tag></tag>
   <elementGuidId>ae6f33a9-067f-49ad-a643-d82cf22dfa5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-0']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.padding-8.overflow-y.full-width.step-box-inside</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a8e70f7-945d-49a3-b04b-3cd6517abf2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-8 overflow-y full-width step-box-inside</value>
      <webElementGuid>dd80e483-e865-4179-b583-e65fa4c99f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product Search &amp; Retrieve: v2.0  Product Search ByIds (POST)</value>
      <webElementGuid>10eafc15-c51d-468f-b1c3-f5c49a408b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-0&quot;)/div[@class=&quot;card-body d-flex flex-column border-radius-12 pd-b-20 p-0 justify-content-between align-items-center overflow-y&quot;]/div[@class=&quot;padding-8 overflow-y full-width step-box-inside&quot;]</value>
      <webElementGuid>4c4595c7-04b7-40bd-97bd-0a164c8ec864</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-0']/div/div[2]</value>
      <webElementGuid>bd6dc9ce-6b70-4f78-b70b-9a5d90c62b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='version 0.2.1'])[1]/following::div[19]</value>
      <webElementGuid>87abc7da-6d60-4792-9e55-d92bdeaa9467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flow Details'])[1]/preceding::div[6]</value>
      <webElementGuid>6b1edc23-6ebe-4945-8031-a55b3a6eccb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>54ccc528-4651-494a-aa44-8b45ec21fbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Product Search &amp; Retrieve: v2.0  Product Search ByIds (POST)' or . = 'Product Search &amp; Retrieve: v2.0  Product Search ByIds (POST)')]</value>
      <webElementGuid>dc268cae-d73c-42e0-846b-90b426c1fa28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
