<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dropbox Basic Flow  v4</name>
   <tag></tag>
   <elementGuidId>55b92ce5-32bb-46d3-bd48-a796c7cc5dc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='name-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d27ab09a-1876-44f2-9070-66c552a24695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-0</value>
      <webElementGuid>31828960-5ce2-41ed-80fd-1f9658b07ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>break-word</value>
      <webElementGuid>ce9705fc-8442-4e13-9b50-819ca36be6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dropbox Basic Flow  v4</value>
      <webElementGuid>e8a9292d-df00-4e62-abcc-f653b7025958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-0&quot;)</value>
      <webElementGuid>0df887dd-2876-47a4-92dc-fd0f50f12037</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='name-0']</value>
      <webElementGuid>20028f18-c020-4b9e-bed8-2ec64eb44832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flows-card']/div/div/div[3]/table/tbody/tr/td/div/div</value>
      <webElementGuid>51549c9b-6879-4506-ab5b-4cfc8620f0f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::div[7]</value>
      <webElementGuid>e017220d-7ba8-4c7b-a0ee-7685afa0cddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scheduled'])[1]/following::div[8]</value>
      <webElementGuid>f527b4b5-8795-4fba-805e-c1bcbd34bb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div</value>
      <webElementGuid>69ad5825-afc4-43ce-8b4e-6c1001225f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'name-0' and (text() = 'Dropbox Basic Flow  v4' or . = 'Dropbox Basic Flow  v4')]</value>
      <webElementGuid>97a0a338-3827-4dee-9d64-0959c1f502df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
