<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_4Allportal Hospital Basic Flow  v9</name>
   <tag></tag>
   <elementGuidId>7f04afad-fbe6-46dd-a848-7ca4d42c5b43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='name-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>83042ff9-c681-48b2-9c94-ccba0449070c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-1</value>
      <webElementGuid>6c5a035a-2a28-4597-ab56-c873f7a23fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>break-word</value>
      <webElementGuid>0827af58-c870-459c-871d-9f729ffd72e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4Allportal Hospital Basic Flow  v9</value>
      <webElementGuid>937d0f05-6326-4225-86ee-699b156c5ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-1&quot;)</value>
      <webElementGuid>f9cad426-98a1-4b8f-9fea-a21ee1039024</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='name-1']</value>
      <webElementGuid>46877d80-9817-4900-94a1-da00b9cef550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flows-card']/div/div/div[3]/table/tbody/tr[2]/td/div/div</value>
      <webElementGuid>d534245a-44a2-44b3-a4d8-882d7010b952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v3'])[1]/following::div[11]</value>
      <webElementGuid>7f2777b0-44b2-4974-b6e2-4e813321a3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div</value>
      <webElementGuid>1338bda0-ba98-4722-bed9-f96d80c5cb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'name-1' and (text() = '4Allportal Hospital Basic Flow  v9' or . = '4Allportal Hospital Basic Flow  v9')]</value>
      <webElementGuid>144a8475-c1aa-4e8d-9a1e-f473b1ae87fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
