<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Connection NameConnectorAdditional Sett_04f872</name>
   <tag></tag>
   <elementGuidId>b810ace7-6aea-4258-af42-a8aa0a0260f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-connection']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-body.overflow-auto.font-size-14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1bac8094-f372-4dde-a9e2-d013ad29aad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body overflow-auto font-size-14</value>
      <webElementGuid>ca813034-2119-43af-8caa-11bde5e46dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connection Name*Connector*Additional SettingsHost Name*Authentication*</value>
      <webElementGuid>5494f211-96b9-4ba3-a4c1-73a1e63db385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-connection&quot;)/div[@class=&quot;card border-0 background-fb&quot;]/div[@class=&quot;card-body overflow-auto font-size-14&quot;]</value>
      <webElementGuid>a4759e7b-b30e-436b-b1c2-db8ee5596272</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connection']/div/div[2]</value>
      <webElementGuid>f1baec75-c8e5-4d26-996a-2e321be15687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Connection'])[1]/following::div[3]</value>
      <webElementGuid>4a09d05b-192b-4331-b8e4-1da951364a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>560572cf-66d8-4a40-9bec-56b8f9635190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Connection Name*Connector*Additional SettingsHost Name*Authentication*' or . = 'Connection Name*Connector*Additional SettingsHost Name*Authentication*')]</value>
      <webElementGuid>a3fc6495-29c1-44c8-b86d-a42ddd649bca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
