<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Savedsearches Retrieve all Saved Search_928d09</name>
   <tag></tag>
   <elementGuidId>f30a8b38-6fb0-4cba-8235-84df2c391d77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-0']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.padding-8.overflow-y.full-width.step-box-inside</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c28c8cc-a1dc-4863-8329-a969ce6781c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-8 overflow-y full-width step-box-inside</value>
      <webElementGuid>f6d65947-216e-4ede-bae4-6a3925f90967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Savedsearches: Retrieve all Saved Searches (GET)</value>
      <webElementGuid>21abf32b-0d62-4e86-a051-df3e05f21277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-0&quot;)/div[@class=&quot;card-body d-flex flex-column border-radius-12 pd-b-20 p-0 justify-content-between align-items-center overflow-y&quot;]/div[@class=&quot;padding-8 overflow-y full-width step-box-inside&quot;]</value>
      <webElementGuid>b76b7332-eea2-4f50-85fb-71a254c839c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-0']/div/div[2]</value>
      <webElementGuid>b7de0fe8-d3a0-43b6-9f91-0a382f9c76e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='version 0.2.1'])[1]/following::div[19]</value>
      <webElementGuid>bcdc6aea-8485-4b5b-9e9b-0f2147925b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flow Details'])[1]/preceding::div[6]</value>
      <webElementGuid>95df7600-c849-415d-a934-5df6b49ca42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>fa4b0514-f7a0-4e11-8faa-e33421b06473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Savedsearches: Retrieve all Saved Searches (GET)' or . = 'Savedsearches: Retrieve all Saved Searches (GET)')]</value>
      <webElementGuid>a66166df-f988-43df-86e4-e13a5d027769</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
