<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bria Basic Flow  v1</name>
   <tag></tag>
   <elementGuidId>dd92007f-0de2-4fa6-a327-9ec75b9faa9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='name-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e74edb7c-530e-4253-9524-e53b03504728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-0</value>
      <webElementGuid>c4cc994f-b57c-4f64-9671-d9ae2e480589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>break-word</value>
      <webElementGuid>c5a4f9ea-31f6-41b4-a29b-1c0891f0097a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bria Basic Flow  v1</value>
      <webElementGuid>144902e4-d360-4220-876a-f92eecc0112c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-0&quot;)</value>
      <webElementGuid>eec86632-a7c8-4d72-a17d-60ed8e6990cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='name-0']</value>
      <webElementGuid>cdb2a719-266c-4927-8cf4-6078bf8dfa5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flows-card']/div/div/div[3]/table/tbody/tr/td/div/div</value>
      <webElementGuid>ad94c271-e4a8-4b8d-a79b-5c8c92af9e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::div[7]</value>
      <webElementGuid>f370e29a-00d4-414c-bf86-310691fa8db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scheduled'])[1]/following::div[8]</value>
      <webElementGuid>62617a2f-8e32-4459-a45c-d4ad032f2dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div</value>
      <webElementGuid>70a90199-7076-4a5a-9750-0c30edde6565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'name-0' and (text() = 'Bria Basic Flow  v1' or . = 'Bria Basic Flow  v1')]</value>
      <webElementGuid>211e0c19-492d-45b1-8b71-3a698d77d9b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
