<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DashboardFlowsActivitiesConnectionsConn_3ec134</name>
   <tag></tag>
   <elementGuidId>20d1f48f-7de2-40e8-9feb-38f172533a11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user-layout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#user-layout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1a49b293-2ed2-4eec-b511-0c66ec226f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-layout</value>
      <webElementGuid>fcd33d21-96c0-4a46-b904-9dfb099e61a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex flex-row flex-fill</value>
      <webElementGuid>60bdfa7b-b3a2-454b-86a6-ff539c9993bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DashboardFlowsActivitiesConnectionsConnectorsUsersOrganizationsRolesWebhookHomeConnectionsCreate Help cyangateoneSelect an organizationSharepoint zafer cyangateone Preferencesbgovercin@cyangate.comRole: ROLE_ADMINversion 0.2.1  LogOutCreate ConnectionConnection Name*Connector*Additional SettingsHost Name*Authentication*OauthOauth*Flows*Password*Username*Password*Client IDClient SecretToken UrlScopes (Comma Seperated)BackSave</value>
      <webElementGuid>13e26a84-9f5a-4afd-983b-c51b726a4616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-layout&quot;)</value>
      <webElementGuid>9b6bfaaa-8e3b-4bb3-b2d7-6522346d203a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='user-layout']</value>
      <webElementGuid>44156525-b38c-47ab-b3e1-64c7400f8d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='app']/div)[2]</value>
      <webElementGuid>d2896279-1e25-479e-9880-e19d36383a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>79d694f4-0aa5-4d90-83bc-b280e08f8e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'user-layout' and (text() = 'DashboardFlowsActivitiesConnectionsConnectorsUsersOrganizationsRolesWebhookHomeConnectionsCreate Help cyangateoneSelect an organizationSharepoint zafer cyangateone Preferencesbgovercin@cyangate.comRole: ROLE_ADMINversion 0.2.1  LogOutCreate ConnectionConnection Name*Connector*Additional SettingsHost Name*Authentication*OauthOauth*Flows*Password*Username*Password*Client IDClient SecretToken UrlScopes (Comma Seperated)BackSave' or . = 'DashboardFlowsActivitiesConnectionsConnectorsUsersOrganizationsRolesWebhookHomeConnectionsCreate Help cyangateoneSelect an organizationSharepoint zafer cyangateone Preferencesbgovercin@cyangate.comRole: ROLE_ADMINversion 0.2.1  LogOutCreate ConnectionConnection Name*Connector*Additional SettingsHost Name*Authentication*OauthOauth*Flows*Password*Username*Password*Client IDClient SecretToken UrlScopes (Comma Seperated)BackSave')]</value>
      <webElementGuid>b3d604ba-0341-402c-a29e-ff4a57112988</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
