<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Connection NameConnectorDropbox Setting_ff98f8</name>
   <tag></tag>
   <elementGuidId>27879412-431d-458a-9b03-e421a0aaf0e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit-connection']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-body.overflow-auto.font-size-14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0ff9e2b-e131-4c1a-8789-d7382b8d01a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body overflow-auto font-size-14</value>
      <webElementGuid>17f49951-b9e6-4aba-b947-040dc1352161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connection Name*Connector*Dropbox SettingsEndpoint*Authentication*</value>
      <webElementGuid>2a6d4b8a-e6f1-4ef4-8a1f-a954fe986746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-connection&quot;)/div[@class=&quot;card border-0 background-fb&quot;]/div[@class=&quot;card-body overflow-auto font-size-14&quot;]</value>
      <webElementGuid>d455f959-c4f8-4d71-8272-da023b44511e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connection']/div/div[2]</value>
      <webElementGuid>33146a56-ab0e-4731-a02b-d097c866ae14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Connection'])[1]/following::div[3]</value>
      <webElementGuid>25da748e-1f47-4cbd-925b-bcd163a0a0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>067f4962-589d-4247-992e-68a04a590e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Connection Name*Connector*Dropbox SettingsEndpoint*Authentication*' or . = 'Connection Name*Connector*Dropbox SettingsEndpoint*Authentication*')]</value>
      <webElementGuid>1d8d0780-563e-41ab-aab5-2d709febd16a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
