<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drive Get my files (GET)</name>
   <tag></tag>
   <elementGuidId>4d6cdb10-00e9-49d0-b8ae-866ab0cd00bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-0']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.padding-8.overflow-y.full-width.step-box-inside</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3aa7c923-a3bb-4cb1-87a6-a57781facb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-8 overflow-y full-width step-box-inside</value>
      <webElementGuid>0e72fa08-46b7-4463-a69c-505ccc5dcb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drive: Get my files (GET)</value>
      <webElementGuid>caf85b51-7771-4c3a-8aac-9bdd257adad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-0&quot;)/div[@class=&quot;card-body d-flex flex-column border-radius-12 pd-b-20 p-0 justify-content-between align-items-center overflow-y&quot;]/div[@class=&quot;padding-8 overflow-y full-width step-box-inside&quot;]</value>
      <webElementGuid>fdc26a21-b0fe-4bdd-b7b5-77e5b09b860d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-0']/div/div[2]</value>
      <webElementGuid>e50df4e5-c1e7-494d-99d5-ce2fab0d8901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='version 0.2.1'])[1]/following::div[19]</value>
      <webElementGuid>249e6e52-ce36-4710-a399-2f6f7d1f4e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flow Details'])[1]/preceding::div[6]</value>
      <webElementGuid>e5df4452-bdea-4b76-9f51-ee50e07f60c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>a703891e-4dcd-42e2-96cd-a3020169121a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Drive: Get my files (GET)' or . = 'Drive: Get my files (GET)')]</value>
      <webElementGuid>8249e97e-ea7b-43bc-b543-f181df40f379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
