<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sharepoint basic flow  v2</name>
   <tag></tag>
   <elementGuidId>97f5e7b2-4711-424b-a9cb-6a8942643302</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='name-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1707edad-915d-4bfb-bfde-7d5582a09cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-8</value>
      <webElementGuid>19217af4-a6b0-4666-b4f5-875ffa983bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>break-word</value>
      <webElementGuid>1fc80a64-f00f-4c4c-96b3-c7316f5a75c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sharepoint basic flow  v2</value>
      <webElementGuid>aa970270-8a3a-43a7-8478-feab2b6a6a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-8&quot;)</value>
      <webElementGuid>31d1da7c-a395-4f6e-96fc-7d164ee4d035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='name-8']</value>
      <webElementGuid>b8a35dde-d970-40a6-99f2-26deaad16e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flows-card']/div/div/div[3]/table/tbody/tr[9]/td/div/div</value>
      <webElementGuid>8d8822e3-7fb5-47d3-a112-da510af761cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v5'])[1]/following::div[11]</value>
      <webElementGuid>3207fffd-91e1-4a6d-8b66-33aac091a9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td/div/div</value>
      <webElementGuid>3dd22066-d901-4593-82f9-d0edb99bf39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'name-8' and (text() = 'Sharepoint basic flow  v2' or . = 'Sharepoint basic flow  v2')]</value>
      <webElementGuid>9fdd8f31-473a-4e6d-9752-9b265088cf93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
