<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0dd9ab45-2fe1-4824-9c17-018836a8d128</name>
   <tag></tag>
   <elementGuidId>7712efa7-6e56-465a-b501-7f4a067abe26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='#/properties/uuid-div']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2315bce2-8370-4d7c-9085-40fd6ca85378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>#/properties/uuid-div</value>
      <webElementGuid>a5347f2d-d8ee-4934-8dd8-3b6e253cc290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control root-div</value>
      <webElementGuid>2baaeb88-ecd5-43b1-85b0-aca2d045aa29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>70046c59-0a5f-464e-88b7-67594884f181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1a26a639-efcf-4233-bffa-29675b65b059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0dd9ab45-2fe1-4824-9c17-018836a8d128</value>
      <webElementGuid>b7cbdfe4-c77e-42a8-891f-aa6a6dfe9272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#/properties/uuid-div&quot;)</value>
      <webElementGuid>3aab94b6-1b02-4e8f-a997-07313bb116d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='#/properties/uuid-div']</value>
      <webElementGuid>9db8be73-6e37-4513-8c74-5850d87abfa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action-form-wrapper']/div/div/div/div/div/div/div</value>
      <webElementGuid>ffc7bfa3-aa35-47b1-acd5-3a6c80f3f16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::div[4]</value>
      <webElementGuid>f3986a1f-aad9-454d-bf9f-766d81aba251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='f'])[1]/preceding::div[3]</value>
      <webElementGuid>29ee69c5-5ba0-4e63-b4ee-f4b8c6c8dc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/preceding::div[3]</value>
      <webElementGuid>2e5f3743-0cde-4571-ae95-10d31748739a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0dd9ab45-2fe1-4824-9c17-018836a8d128']/parent::*</value>
      <webElementGuid>1c3de591-dbcb-438d-beba-61be965ab9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>4c2a5ba0-1468-4f00-8995-970a0b0140b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '#/properties/uuid-div' and (text() = '0dd9ab45-2fe1-4824-9c17-018836a8d128' or . = '0dd9ab45-2fe1-4824-9c17-018836a8d128')]</value>
      <webElementGuid>9292f876-5c33-45df-807f-7347a6571fab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
