<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Customer Data Get Metadata (GET)</name>
   <tag></tag>
   <elementGuidId>0d001c97-4680-496b-b806-01378f15fd7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.padding-8.overflow-y.full-width.step-box-inside</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-0']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b8605c01-15ad-4a86-9079-94d03d34d9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-8 overflow-y full-width step-box-inside</value>
      <webElementGuid>00bec567-6300-4edb-9e73-80bc4fcfaa3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer Data: Get Metadata (GET)</value>
      <webElementGuid>129654d8-6bd2-4141-af88-7711c0f40be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-0&quot;)/div[@class=&quot;card-body d-flex flex-column border-radius-12 pd-b-20 p-0 justify-content-between align-items-center overflow-y&quot;]/div[@class=&quot;padding-8 overflow-y full-width step-box-inside&quot;]</value>
      <webElementGuid>9cb8f8ce-07d7-4664-be35-0ee0094ce3b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-0']/div/div[2]</value>
      <webElementGuid>bb13c172-2c50-4691-8819-48ba6a826670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='version 0.2.1'])[1]/following::div[19]</value>
      <webElementGuid>beebd6f8-80f9-4cbe-9817-3fc05c877135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flow Details'])[1]/preceding::div[6]</value>
      <webElementGuid>efa387f4-71bf-43f5-aa3a-3e482bb22348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>38848ef0-4c92-4560-9b1e-6d7b917a6bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Customer Data: Get Metadata (GET)' or . = 'Customer Data: Get Metadata (GET)')]</value>
      <webElementGuid>a2ca1f18-2e4e-4605-bef3-2cc5c9c0b738</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
