<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aws-oneteg-test-assets connection Katalon Test</name>
   <tag></tag>
   <elementGuidId>1ed52861-1e22-4325-80ea-eef454237f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='name-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>777a0c59-1a95-4be0-92c3-950a6fb49e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-0</value>
      <webElementGuid>7cacb157-571a-4683-8d05-f7c16db02a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aws-oneteg-test-assets connection Katalon Test</value>
      <webElementGuid>91fa48ee-316a-447e-acf2-3806f77bb93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-0&quot;)</value>
      <webElementGuid>f271b74f-df51-440f-b8ba-2dec371f2fdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='name-0']</value>
      <webElementGuid>5f22d287-f037-4da4-ab26-8d5d0ecb4fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show-connections']/div/div/div/div[3]/table/tbody/tr/td/div/div</value>
      <webElementGuid>dd70ad91-5280-45ae-83f6-409b7fbc29c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authentication'])[1]/following::div[7]</value>
      <webElementGuid>0bfbd4aa-721e-4428-b43d-96dafbc768e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connector'])[1]/following::div[8]</value>
      <webElementGuid>d5cda0f6-44ad-4327-810a-2a8c3d4fab8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div</value>
      <webElementGuid>c52c7260-2fe5-4d13-91a7-ea1a235021dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'name-0' and (text() = 'Aws-oneteg-test-assets connection Katalon Test' or . = 'Aws-oneteg-test-assets connection Katalon Test')]</value>
      <webElementGuid>c54fc48a-9bc2-4813-bfa3-bfac5b775eef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
