<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OpenAI Creates an image given a prompt. (POST)</name>
   <tag></tag>
   <elementGuidId>f1347e96-5469-4140-ba67-a376a863e8d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-0']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.padding-8.overflow-y.full-width.step-box-inside</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5e68912-4193-45e2-b032-39a849c2d3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-8 overflow-y full-width step-box-inside</value>
      <webElementGuid>d9a0228c-7f40-4e5f-8de9-8e5e1a0524d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OpenAI: Creates an image given a prompt. (POST)</value>
      <webElementGuid>b133e0f5-8fef-45f2-966f-d0090db1acf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-0&quot;)/div[@class=&quot;card-body d-flex flex-column border-radius-12 pd-b-20 p-0 justify-content-between align-items-center overflow-y&quot;]/div[@class=&quot;padding-8 overflow-y full-width step-box-inside&quot;]</value>
      <webElementGuid>82587fe9-9e8d-41a1-8c99-41907a0b9f8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-0']/div/div[2]</value>
      <webElementGuid>a2907978-cbdb-4bb8-a5c9-f68bebe2a81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='version 0.2.1'])[1]/following::div[19]</value>
      <webElementGuid>8b9f3985-f695-4648-a182-35505768a0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flow Details'])[1]/preceding::div[6]</value>
      <webElementGuid>ba08c71f-10f2-4fb9-8e39-4d97d777f7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>5c7612a0-e20a-47b5-8c12-bfe1d7be67c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'OpenAI: Creates an image given a prompt. (POST)' or . = 'OpenAI: Creates an image given a prompt. (POST)')]</value>
      <webElementGuid>5cfa3683-9826-472e-a909-42141e04faab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
