<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Akeneo Basic Flow  v1</name>
   <tag></tag>
   <elementGuidId>9c5d4afc-3763-46e5-9118-26a7a3c3d013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='name-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d1675a3-85fe-4166-9f97-d804cc6fc284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-1</value>
      <webElementGuid>6f6efd65-480b-43e7-8fc0-416d70c3c329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>break-word</value>
      <webElementGuid>44e895ff-547e-4ab8-9bf0-f7023ec2d1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akeneo Basic Flow  v1</value>
      <webElementGuid>f5f69095-1887-42e0-b2c1-a28a231ae65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-1&quot;)</value>
      <webElementGuid>865b275f-f832-4172-b1b1-ed9b7ba7a1ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='name-1']</value>
      <webElementGuid>07bf09be-645c-489a-8967-5575e7dad6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flows-card']/div/div/div[3]/table/tbody/tr[2]/td/div/div</value>
      <webElementGuid>4874e8d2-5bbf-4321-9d2b-a390c29d26a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v1'])[1]/following::div[11]</value>
      <webElementGuid>779ab2df-aeff-4406-b80c-47def30c6fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div</value>
      <webElementGuid>eee63e8f-4c79-4210-9ca0-4d37d2f97b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'name-1' and (text() = 'Akeneo Basic Flow  v1' or . = 'Akeneo Basic Flow  v1')]</value>
      <webElementGuid>164f57c9-7cc7-4a3e-aa47-85c800077d68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
