<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3-4Allportal Hospital Basic Flow  v8</name>
   <tag></tag>
   <elementGuidId>4e233082-5057-4cae-a111-cd980af7e1d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='name-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3fad6fdd-9779-4c48-9d41-4d616e6d89a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-0</value>
      <webElementGuid>63a3f8fd-a41d-4e49-b452-f49f533b361f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>break-word</value>
      <webElementGuid>a0bc34c0-1702-4630-9cc8-9a65361178dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3-4Allportal Hospital Basic Flow  v8</value>
      <webElementGuid>4e4aed4b-06c1-4198-82eb-c01b5a346a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-0&quot;)</value>
      <webElementGuid>38f04587-af82-4a1a-83ba-4aafc4259200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='name-0']</value>
      <webElementGuid>e5436e20-273b-447f-a716-b3417fea56a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flows-card']/div/div/div[3]/table/tbody/tr/td/div/div</value>
      <webElementGuid>8ef4ee7d-2c6e-49bb-a40b-4242159bf823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::div[7]</value>
      <webElementGuid>35ba30c3-dc5f-43a0-b8d3-65362545a7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scheduled'])[1]/following::div[8]</value>
      <webElementGuid>2c61b562-7ab9-4318-8731-2e6dcc7705b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div</value>
      <webElementGuid>473356e8-8a54-498a-ab30-e0afb417a755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'name-0' and (text() = '3-4Allportal Hospital Basic Flow  v8' or . = '3-4Allportal Hospital Basic Flow  v8')]</value>
      <webElementGuid>d3273216-6908-4e24-8a30-48d3225f3b11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
