<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1_1_2</name>
   <tag></tag>
   <elementGuidId>be9c7f7f-34f9-42e7-9a4f-5898304479c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='#/properties/queryParam:num_synthetic_results_per_page-div']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>95a49df4-a3a0-4f19-84d4-e18fb3a58e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>#/properties/queryParam:num_synthetic_results_per_page-div</value>
      <webElementGuid>16e3ddb6-b223-4a58-941f-4efdbaed61ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control root-div</value>
      <webElementGuid>0d1ead41-6229-4f9d-afef-574b07d0f26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>39e85f37-f54e-4e44-8f10-36b3aadfbeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>41f746bc-ff44-4f19-95b1-f5a7a0e7fc54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5c861d74-caa2-4435-b77e-6123c85dba0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#/properties/queryParam:num_synthetic_results_per_page-div&quot;)</value>
      <webElementGuid>1016a0cb-6928-45a0-8d29-67bb462c5c99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='#/properties/queryParam:num_synthetic_results_per_page-div']</value>
      <webElementGuid>228f1572-834f-490a-ae32-9cf237344fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action-form-wrapper']/div/div[10]/div/div/div/div/div</value>
      <webElementGuid>69e47c75-bd03-455f-bf3f-867d7b820138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Num Synthetic Results Per Page'])[1]/following::div[4]</value>
      <webElementGuid>b70d67d5-5c5d-4a2f-b9ae-d20b3f67b406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[1]/following::div[7]</value>
      <webElementGuid>19cd8483-1244-47e1-ab9d-3608fd6ddc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='f'])[5]/preceding::div[3]</value>
      <webElementGuid>fae464e8-989d-4e15-b746-6c9ff68ef27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[5]/preceding::div[3]</value>
      <webElementGuid>eef0c719-3771-478c-a3c7-b55554da6592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div</value>
      <webElementGuid>d5a60574-6065-4743-bec0-6de94beb02d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '#/properties/queryParam:num_synthetic_results_per_page-div' and (text() = '1' or . = '1')]</value>
      <webElementGuid>7b08b2ac-e036-4c7f-98e0-8d164096b8a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
