<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_login-password-show-icon</name>
   <tag></tag>
   <elementGuidId>8fd32d0d-087b-4ede-b02a-7b6c05f7ee32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-password-show-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='login-password-show-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3209aa6e-f822-4401-b2ed-5759c23bd0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__icon el-icon-view el-input__clear</value>
      <webElementGuid>09c0f4ae-4be1-40ca-9c33-30ec6ef14861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-password-show-icon</value>
      <webElementGuid>b604b857-1c56-4e4b-8cf6-799bb0f876f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>test-id</name>
      <type>Main</type>
      <value>login-password-show-icon</value>
      <webElementGuid>e786f185-9991-4ad0-bc28-fbfd18654cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-password-show-icon&quot;)</value>
      <webElementGuid>14d27e7e-f99b-40ee-a568-f5eb5e5583f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='login-password-show-icon']</value>
      <webElementGuid>61b26169-feba-46ca-a8b3-8d6cc5417b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div[2]/form/div[2]/div/div/span/span/i</value>
      <webElementGuid>743c77dc-f18c-4f4b-b04e-52d2b4e94556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>c80dc128-66ca-4a98-ac49-613f5e3fbbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'login-password-show-icon']</value>
      <webElementGuid>cffa5473-d78f-44bf-9e1c-7d605b338070</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
