<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LogOut_logo-step-header</name>
   <tag></tag>
   <elementGuidId>69e3bb60-9cb4-4f1d-a1b7-2bb1141117fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.logo-step-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-0']/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>60584d21-e8fa-4170-abf9-a201c56fe405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-step-header</value>
      <webElementGuid>caae7bbb-1230-4899-8148-828bd2c8fa84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1ilvdybj0vjbh.cloudfront.net/briaConnector-v1.0-f-f.png</value>
      <webElementGuid>78b2e196-54ee-4add-9c92-830822712f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>d005adc6-6147-4edd-913a-5fc8fd6738c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9186322d-2ec2-45ce-95ce-30633f30b638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-0&quot;)/div[@class=&quot;card-body d-flex flex-column border-radius-12 pd-b-20 p-0 justify-content-between align-items-center overflow-y&quot;]/div[@class=&quot;d-flex align-items-center width-100 justify-content-center logo-header&quot;]/div[@class=&quot;img-box d-flex align-items-center justify-content-center&quot;]/img[@class=&quot;logo-step-header&quot;]</value>
      <webElementGuid>acd3bf6c-f117-42e8-9fe0-f93aa6736018</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-0']/div/div/div/img</value>
      <webElementGuid>0e29e4a0-71d3-41cb-9ae8-229ee18f00ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='logo'])[2]</value>
      <webElementGuid>d3784136-8eb9-4f32-9549-88a79b55bdb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/img</value>
      <webElementGuid>328f04ba-be2c-4732-999e-430b4941588e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1ilvdybj0vjbh.cloudfront.net/briaConnector-v1.0-f-f.png' and @alt = 'logo']</value>
      <webElementGuid>091a92b3-c6c8-4e47-afc1-6bb8eb3d6870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
