<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Token Url_propertiestokenUrl-input</name>
   <tag></tag>
   <elementGuidId>be83fbaf-cb65-43f1-9691-a1fb62c2fd86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='#/properties/tokenUrl-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24f35c15-2e2f-4185-85f2-cca37fbae312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>#/properties/tokenUrl-input</value>
      <webElementGuid>eff0c760-7215-47a8-abea-cf85005cd23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input form-control</value>
      <webElementGuid>8dacc278-ded9-47e7-8aa7-085fc5c6475d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83d99f11-5ee3-4928-a000-ceefb9cba94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#/properties/tokenUrl-input&quot;)</value>
      <webElementGuid>a54a61bf-325e-483d-9a0d-900ebdb70cb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='#/properties/tokenUrl-input']</value>
      <webElementGuid>90ac592f-71be-42cf-a9fa-a313825d5897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connection']/div/div[2]/div/div[3]/div[2]/div/div[2]/div/div/div/div[2]/div/div[5]/div/div/input</value>
      <webElementGuid>56a2de2d-ad69-4484-83fd-d91f6f26f378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>0f91eb71-cd4d-46a3-8c68-c70bc48b8f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '#/properties/tokenUrl-input' and @type = 'text']</value>
      <webElementGuid>cd9ad61e-d00e-4459-b967-99aceaf362b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
