<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__connection-connector-select</name>
   <tag></tag>
   <elementGuidId>d5afe0a1-da22-4201-98bc-19c25fb06d54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connection-connector-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='connection-connector-select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33d2b245-a668-482b-b3f8-9f4dea1ccb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>2754897a-7c9d-4a6b-ac89-f1dbea7c7730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-connector-select</value>
      <webElementGuid>600fdb5d-e1d4-4cfe-9d4a-b7d971e0d07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4ad81c7-530f-43ee-b912-9543c85a2f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>db3a0bf6-19b2-4cab-82b1-6f5fbb2958a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select a connector.</value>
      <webElementGuid>a70067e4-f3f9-48c1-9212-dd37b7df3c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-connector-select&quot;)</value>
      <webElementGuid>65d0a8d2-66de-4700-89c7-6bea07649d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='connection-connector-select']</value>
      <webElementGuid>7293cb91-05c2-4e1c-91c9-43c7c3be45cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connection']/div/div[2]/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>c9057268-367c-47a2-8875-80c5553df32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>42b913bb-5ef0-4332-ba66-de5608b04ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'connection-connector-select' and @type = 'text' and @placeholder = 'Select a connector.']</value>
      <webElementGuid>f2371f67-7fee-4659-af2d-6377dfe2bc65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
