<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__connector-pricing-type</name>
   <tag></tag>
   <elementGuidId>719951b2-5cf5-49f0-aba6-d8266d694955</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='connector-pricing-type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connector-pricing-type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d52f9f9-ae67-491c-9217-f18f56e2667f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>86766379-5560-444c-b7c1-34314b8ddc7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connector-pricing-type</value>
      <webElementGuid>ab4ca7fe-f390-4d07-8aa3-f2de623140fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a13f2ff-5544-40db-8505-4a848be4ddff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3d1e519a-5d34-4dee-8d0d-78db104e7edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select a connector type.</value>
      <webElementGuid>e6ce3397-2844-495b-9fc4-248350d654f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connector-pricing-type&quot;)</value>
      <webElementGuid>1655916f-73d3-401e-a270-0f06cdeac5d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='connector-pricing-type']</value>
      <webElementGuid>3e42078b-3761-4201-9d0c-4a7d754135a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connector']/div/div[2]/div/div/div[6]/div/div/div/input</value>
      <webElementGuid>9f9227f9-68fb-4fff-ad70-c4f998c9ba4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>b3fbc9b8-425e-4727-a43e-be1853a95c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'connector-pricing-type' and @type = 'text' and @placeholder = 'Select a connector type.']</value>
      <webElementGuid>3d2c6422-a27d-4d5b-b56b-a5acf4c83790</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
