<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__flow-connection-select</name>
   <tag></tag>
   <elementGuidId>ceafedc4-8268-47a7-8d4f-f5933ffa0fc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flow-connection-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flow-connection-select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79b93182-d65d-452d-8d09-e77bcdd9e045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>8a5ad69f-f83a-49cc-9f5b-d20b30ddb4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flow-connection-select</value>
      <webElementGuid>c1144c7b-e747-48c0-9527-cd3cecb10fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b9dfcb8-c4bb-4fe8-9bae-f4fe349a90c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>77b965c2-398f-48f2-9134-8428ee93beb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bria Connection</value>
      <webElementGuid>61813bfd-41e1-45d7-98ef-dec37da18b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flow-connection-select&quot;)</value>
      <webElementGuid>65021ad0-25af-4e5e-8242-a5675b3ffb87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flow-connection-select']</value>
      <webElementGuid>9e50ac03-ceca-44ab-863f-a9378d3384e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='connection']/div/div/div/input</value>
      <webElementGuid>97d504ec-1ede-4e03-b24d-fe2aeb0acf36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>b4bebc0f-4767-4fc8-83e0-f6ad67eee656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'flow-connection-select' and @type = 'text' and @placeholder = 'Bria Connection']</value>
      <webElementGuid>5281a0c6-ac44-4743-bf51-22d9adfe305d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
