<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__propertieshostName-input</name>
   <tag></tag>
   <elementGuidId>4da11b02-7c86-4e77-a4e1-87033e92697d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='#/properties/hostName-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19339f10-36d6-4a72-a4ac-9bd2d8a31135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>#/properties/hostName-input</value>
      <webElementGuid>8bbb833f-d8c7-40c3-a9e2-6ccc3a3c4752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input form-control</value>
      <webElementGuid>0c85c3c9-9ce9-4643-860e-2fd8b031786c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e1c5ea23-bc1d-414a-9f75-763cb6cd2bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#/properties/hostName-input&quot;)</value>
      <webElementGuid>34d99135-bd34-4d15-8d25-9c4407678ce5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='#/properties/hostName-input']</value>
      <webElementGuid>116d4262-c3b9-4d2b-82cf-c84acb69cf2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connection']/div/div[2]/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>bc50137b-ae7b-4bca-888d-cfcc1052e6e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/input</value>
      <webElementGuid>2d86a981-f965-4cff-a640-e9e080e051f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '#/properties/hostName-input' and @type = 'text']</value>
      <webElementGuid>34ded416-fe75-4860-9b6a-b5af19f15611</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
