<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__connection-authentication-type</name>
   <tag></tag>
   <elementGuidId>47726c26-db7c-4976-90a2-e4937919a46c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connection-authentication-type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='connection-authentication-type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c806498-d937-4af4-a73b-1abfc8b394f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>febef04d-74cf-4693-a410-918af467d2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-authentication-type</value>
      <webElementGuid>5737249e-3568-4750-a83f-6a030b18a90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b559b11-6a70-4736-ace1-f3e507ccce6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>af63593d-9ff4-4b9f-b00d-e13b0986ca31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select auth type.</value>
      <webElementGuid>8fbe3e49-63b0-4a6f-950b-40459c89dd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-authentication-type&quot;)</value>
      <webElementGuid>7df1f089-a79f-4154-a54b-6e2a2c71efb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='connection-authentication-type']</value>
      <webElementGuid>60f968d8-3d69-472c-bc30-0196a0732113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connection']/div/div[2]/div/div[3]/div[2]/div/div/div/div/input</value>
      <webElementGuid>6c3ce026-0768-4c2e-8dd6-5db15c662cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>42c48308-18d6-49a8-bfa0-9c33f5cf2bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'connection-authentication-type' and @type = 'text' and @placeholder = 'Select auth type.']</value>
      <webElementGuid>887b7966-d718-42ea-a64f-2d2ca0909085</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
