<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Valid Password_confirm_password</name>
   <tag></tag>
   <elementGuidId>a2b32b86-e2e6-475b-91eb-44d708c32551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirm_password</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;confirm_password&quot;)[count(. | //input[@class = 'el-input__inner' and @id = 'confirm_password' and @type = 'password' and @autocomplete = 'off' and @placeholder = 'Confirm Password']) = count(//input[@class = 'el-input__inner' and @id = 'confirm_password' and @type = 'password' and @autocomplete = 'off' and @placeholder = 'Confirm Password'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirm_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ffa1e54-eaaf-40de-a7e0-5239ff7ea168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>7e751de4-57e2-4211-922d-3b2bf61dd6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm_password</value>
      <webElementGuid>3e50394d-0fd2-4329-b6cf-86f5226e789f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>369436eb-a032-4d9c-808e-91aeae5f4bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bc52a8d5-29f5-4c3f-9ea5-ff0131d7a50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>37825a54-054b-4c29-81dd-9fa7e8904946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm_password&quot;)</value>
      <webElementGuid>b13a8ad5-1348-4091-ac4c-371491d10123</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirm_password']</value>
      <webElementGuid>3ae70e1b-3823-4789-aa43-dfcb01bc615c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/form/div[3]/div/div/input</value>
      <webElementGuid>7a50f295-3ea3-40c4-a11f-eaf717cfdcf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>3d9377ca-6eae-4a75-95b0-57fbf2a5c033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirm_password' and @type = 'password' and @placeholder = 'Confirm Password']</value>
      <webElementGuid>8016681e-81ca-4faf-a805-fed86ded94ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
