<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Organization_user-organization</name>
   <tag></tag>
   <elementGuidId>25643e1d-d11c-467f-b15d-0c93e052de6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user-organization</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user-organization']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3005baf-d014-4ecf-86b4-21e32a2e351c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>2acfdd4e-9d85-4620-939b-e822fa71bb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-organization</value>
      <webElementGuid>f2ff2ed4-e305-49e8-a3e2-779c4c02700f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b73993a-b828-4cc1-a3ba-2677d6e25d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>639314f2-4b6f-4ed1-bda9-dc7aefa46e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select an organization</value>
      <webElementGuid>bc6bc99a-d95d-45f4-b566-4e58375141c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-organization&quot;)</value>
      <webElementGuid>9b1aa069-1039-438a-8a99-c0242a409e62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user-organization']</value>
      <webElementGuid>56d654ba-5ccf-465d-871a-8146913c0598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-user']/div/div[2]/div/div[5]/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>d152473e-0fba-4d3c-aeaa-28b16c6b16f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>ad569f0a-5cae-40b4-b2bb-cda553f7126d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user-organization' and @type = 'text' and @placeholder = 'Select an organization']</value>
      <webElementGuid>a3531092-dc90-4446-b49d-10f1a28227c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
