<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__connection-basic-username</name>
   <tag></tag>
   <elementGuidId>fc5abb2d-8ff5-46ce-8e65-bcec4c2e1c1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connection-basic-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='connection-basic-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e051bdd-f39c-4da7-93e7-386183c8643a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>5f4df128-97db-4913-b2f0-b7bdf9863b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-basic-username</value>
      <webElementGuid>8122fda5-b11d-40dd-9561-ea16ab0af4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4d73418-2d1a-4e25-a377-8c7b5a941960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2662fce7-d5cf-4b3c-9557-824464037f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User Name</value>
      <webElementGuid>728d2229-23a6-4c92-b0cb-6f78520a1de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-basic-username&quot;)</value>
      <webElementGuid>f951eda2-2705-4c5a-9725-67be40dabe77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='connection-basic-username']</value>
      <webElementGuid>1ebe2072-9eed-40dd-abb7-cf517c331078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connection']/div/div[2]/div/div[3]/div[3]/div/div/input</value>
      <webElementGuid>84ca62b1-c46e-4c26-add6-1ddfd10482b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>ede7f691-9a57-4616-97bc-4cf31ec87dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'connection-basic-username' and @type = 'text' and @placeholder = 'User Name']</value>
      <webElementGuid>72cd7869-dd4c-4220-8cc7-babdb5907916</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
