<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Page_propertiesqueryParampage-input</name>
   <tag></tag>
   <elementGuidId>5085ab55-5e6f-48a3-bd01-fb656b56d55e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='#/properties/queryParam:page-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>775fb61a-c28d-4b80-8f69-ba1aebe86a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>#/properties/queryParam:page-input</value>
      <webElementGuid>aaadb3da-ebf1-4fbe-baad-4d02184af58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input form-control</value>
      <webElementGuid>027eed22-0e05-420e-9531-a075481aa23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#/properties/queryParam:page-input&quot;)</value>
      <webElementGuid>78b47769-0534-46f4-b4c0-1204625ce12f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='#/properties/queryParam:page-input']</value>
      <webElementGuid>b33ce5fc-62ad-4d59-90ff-856eb49cbdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action-form-wrapper']/div/div[5]/div/div/div/div/input</value>
      <webElementGuid>8ed4b0d0-d19e-42b8-8e0c-0bb85c505108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/input</value>
      <webElementGuid>355910fa-3c90-4816-ab7a-f97b882d76e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '#/properties/queryParam:page-input']</value>
      <webElementGuid>324df52c-c77a-4cc0-9867-7aa4db826fad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
