<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__connection-basic-endpoint</name>
   <tag></tag>
   <elementGuidId>0ef11118-5b1d-460a-8482-8a2c988b6506</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connection-basic-endpoint</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='connection-basic-endpoint']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf7f5356-6d02-4ccb-b517-bddad13a1d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>b327b958-d5bd-4e56-a3cf-2a4398ea1f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-basic-endpoint</value>
      <webElementGuid>2a60a830-c04b-45f3-9bd6-cdf5c7042663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>124f9cab-3e41-4e65-96a4-33752612d368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>436edee4-bc9f-4a08-b27a-0d8b94357809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Endpoint</value>
      <webElementGuid>9303f67d-8fa5-4613-a96e-8e650381678d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-basic-endpoint&quot;)</value>
      <webElementGuid>a6f50c61-cfba-454c-a1f5-b16702997498</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='connection-basic-endpoint']</value>
      <webElementGuid>cda3c06e-46fe-40a4-8ebb-aef0b3f8c422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connection']/div/div[2]/div/div[3]/div[3]/div[3]/div/input</value>
      <webElementGuid>499f64a9-9c16-4238-bd29-422c22743a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>c091fc35-7c67-40c8-bcde-8c5c3891d543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'connection-basic-endpoint' and @type = 'text' and @placeholder = 'Endpoint']</value>
      <webElementGuid>0e554af1-267a-4995-bd11-a5515290c25e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
