<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Num Synthetic Results Per Page_proper_d595ef</name>
   <tag></tag>
   <elementGuidId>f4b9c71e-6dcf-4b91-984f-a0025effad6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='#/properties/queryParam:num_synthetic_results_per_page-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63199f03-8a33-44b8-8cf4-44cc9687f995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>#/properties/queryParam:num_synthetic_results_per_page-input</value>
      <webElementGuid>047e9905-1ff4-433c-aa3f-c50dfce7e854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input form-control</value>
      <webElementGuid>b756c963-a3e0-441d-a803-226103a8e5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#/properties/queryParam:num_synthetic_results_per_page-input&quot;)</value>
      <webElementGuid>cfbfac0b-3215-4eea-aaa9-fc7e7b09d548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='#/properties/queryParam:num_synthetic_results_per_page-input']</value>
      <webElementGuid>74c7ca72-9da2-43ff-9ff4-592efc7aaa80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action-form-wrapper']/div/div[10]/div/div/div/div/input</value>
      <webElementGuid>0b15e3de-303a-4317-bb80-7cc2d66c52d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/input</value>
      <webElementGuid>acd9b42f-be5f-4d74-84f8-7bde29660784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '#/properties/queryParam:num_synthetic_results_per_page-input']</value>
      <webElementGuid>5e9e809f-af79-4be4-94e2-4bf201e8289c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
