<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__connection-basic-password</name>
   <tag></tag>
   <elementGuidId>29f380f2-42de-4af3-8e50-457173037ffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connection-basic-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='connection-basic-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9c22c14-a47c-4d2e-a1ec-12f24e661686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>8b835e12-e48f-49e3-a3f7-c0d35463885e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-basic-password</value>
      <webElementGuid>137d65b0-0bcd-4b7a-8cd7-ed56e2885016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f3fd8642-79e6-4094-9d91-14f1e350cac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>77798299-5eaf-494a-911a-1d2941a4f959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>e16d8022-38a1-459e-9174-23bd8c497a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-basic-password&quot;)</value>
      <webElementGuid>09e3d262-4df7-41a3-8127-924a72c6e727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='connection-basic-password']</value>
      <webElementGuid>dacffcf7-1c96-4938-8c82-b46fcccda24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connection']/div/div[2]/div/div[3]/div[3]/div[2]/div/input</value>
      <webElementGuid>6ef24928-8c75-4aa7-b3b0-5fa365a94650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>bac273c0-db60-4bf7-bf0d-3db78fb24ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'connection-basic-password' and @type = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>4ecf3fa6-9aea-47f4-b718-7e2a712a6576</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
