<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Organization_user-role</name>
   <tag></tag>
   <elementGuidId>b244fce1-a166-4a88-ab51-b604e3599a7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user-role</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user-role']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d4bf925-9bee-4543-829c-cabee6b4695f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>ef18c6ce-1a1d-4aff-ba62-6fb47cc3b22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-role</value>
      <webElementGuid>13baa374-f29b-4b25-bf67-5aca079b0ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a40a8484-33f3-4ae2-a74b-0e1025a3c4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dd055d50-ea86-4a82-8aac-8536df3dfe05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select a role</value>
      <webElementGuid>b24b0dff-852b-4d2c-8d9b-13c19781af46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-role&quot;)</value>
      <webElementGuid>acb06805-afa4-44f4-a529-397fa6bf5438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user-role']</value>
      <webElementGuid>d8e04d55-f32f-4dd1-9ce0-6fe98bb3d0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-user']/div/div[2]/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>194c975a-c6b1-4fa4-b7bc-23a8747ff6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>93dbe533-c56b-41a1-8b19-7accd3fd4664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user-role' and @type = 'text' and @placeholder = 'Select a role']</value>
      <webElementGuid>7f04172e-5416-4a47-b14f-ff525d271de3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
