<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Synchronous_propertiesqueryParamsynch_7d3244</name>
   <tag></tag>
   <elementGuidId>326c59e9-3df8-4933-bbf1-136cf9e9af48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='#/properties/queryParam:synchronous-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d53b5893-80d5-4ef3-82de-80820c267df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>59197343-fcb1-4168-a1f3-17579cc849f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>d62cf474-6ed0-4ecd-96d7-62f0c89a8e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>#/properties/queryParam:synchronous-input</value>
      <webElementGuid>13048fc1-2c56-4c5e-afe5-e490a5ffdbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#/properties/queryParam:synchronous-input&quot;)</value>
      <webElementGuid>7e3ba2d7-b2ae-4628-b5e4-8c74e7097270</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='#/properties/queryParam:synchronous-input']</value>
      <webElementGuid>76fb83e4-7e5d-4e87-99c7-c7d17b69e50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action-form-wrapper']/div/div[11]/div/div/div/input</value>
      <webElementGuid>a3aff125-0ba9-474b-b3aa-c689c59b8bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/input</value>
      <webElementGuid>844c7679-1118-4f59-b1d9-df71f8241da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = '#/properties/queryParam:synchronous-input']</value>
      <webElementGuid>d5ce7453-ff7b-4198-81cb-39a95b8cebd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
