<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user-email</name>
   <tag></tag>
   <elementGuidId>35ab4c85-58be-40f8-87d5-0c814806d206</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user-email</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'user-email' and @type = 'text' and @placeholder = 'Email']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d93e8bda-3d9d-4bcd-aa0b-82e4fc9d8524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>1bdf5682-a09e-42a1-b052-b2cd86e3ac6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>test-id</name>
      <type>Main</type>
      <value>user-email</value>
      <webElementGuid>6059e9b3-1ec2-4033-ac0c-e6339c0fa529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-email</value>
      <webElementGuid>0ed037c6-5566-4525-ad7e-349c5ad0cc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8ab7552-ef5d-4e16-8b7b-667606280517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>90f14894-9ecd-4302-bca6-b2c749581adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>0f1d3c97-af08-4ff2-903a-029a65bc4bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-email&quot;)</value>
      <webElementGuid>44b00ae0-f034-43a6-8ce9-3a427c7c44e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user-email']</value>
      <webElementGuid>cc866754-187d-4647-b40b-773aee16ed09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-user']/div/div[2]/div/div[3]/div/input</value>
      <webElementGuid>641a2ac5-c77d-4b62-a868-101907ba7464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>85c3bdaa-f51a-44ac-8ade-a7f7221a0f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user-email' and @type = 'text' and @placeholder = 'Email']</value>
      <webElementGuid>bdc0cd7a-6786-4f13-813d-54513fedb666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
