<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Connectors_transfer-check-left-0</name>
   <tag></tag>
   <elementGuidId>afa0713d-6aba-47ea-9b84-b86ba241a61c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transfer-check-left-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transfer-check-left-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dd1dd32-8c25-490c-96d4-8ee2d74c5ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>16052c46-2dcd-4aa9-9825-1d59bde81f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transfer-check-left-0</value>
      <webElementGuid>eefa5a45-6f76-4df2-9975-9932e63e8487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4allportalConnector-v1.0</value>
      <webElementGuid>93d92231-e20b-4518-97c0-c4ab228543fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transfer-check-left-0&quot;)</value>
      <webElementGuid>24ff5956-2127-420c-b99b-c95dacb98ddd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transfer-check-left-0']</value>
      <webElementGuid>a26cea02-3fcd-4d56-8f90-b03200926ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-tenant']/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>f46a6a78-1e3a-431b-8361-f1bc71150c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>2e752efa-68e4-4b7c-8f73-2ea94f0abd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'transfer-check-left-0']</value>
      <webElementGuid>906453f2-d8ed-4da2-adfa-aa5bc2341c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
