<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__propertiesquery-input</name>
   <tag></tag>
   <elementGuidId>8fb53737-5c6d-461b-b5a1-fa6964ffcb23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='#/properties/query-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15cf88b7-1b18-4776-b24b-7bf5a98656a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>#/properties/query-input</value>
      <webElementGuid>9df9e4d2-db03-4737-918a-c93b2935819b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input form-control</value>
      <webElementGuid>4e809d06-0715-42f6-83a1-8570a8bcbcb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#/properties/query-input&quot;)</value>
      <webElementGuid>f61c9fbd-481d-4944-b0bf-0f5e28a58f44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='#/properties/query-input']</value>
      <webElementGuid>28946098-57a8-4967-9257-dcdab1aed149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion-searchfilesdropbox-0-0-0']/div/div/div/div/div/div/div/input</value>
      <webElementGuid>9849b94c-d147-4d26-aa65-3312e3d40715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>9240cf1d-2123-4fb2-9d9d-d069582a90f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '#/properties/query-input']</value>
      <webElementGuid>ef076d1a-3b7a-4bc3-8f8c-9f2444114ff3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
