<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__flow-action-select</name>
   <tag></tag>
   <elementGuidId>66a9b241-9bab-4143-b7fb-110076f36636</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flow-action-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flow-action-select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c7f6739-52b6-429e-9183-b3cbdee78aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>6347157d-9e0e-4bfa-b688-3951f79b4435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flow-action-select</value>
      <webElementGuid>4846c1da-965e-44b5-9275-0d36d0055bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce0d8f08-d56e-4b94-8a19-e60641c27cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8da3db39-d59a-4476-ac95-934497dd1c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select an action</value>
      <webElementGuid>93ec55e4-a0f0-4017-88d2-5a14aa4fecaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flow-action-select&quot;)</value>
      <webElementGuid>2f43a712-6dab-4799-9fba-36e2cb001dec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flow-action-select']</value>
      <webElementGuid>0eb38b79-6b8d-4d36-8530-01d1aec7a689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action']/div/div/div/input</value>
      <webElementGuid>7e3be921-0e60-4283-a26e-c21824a39fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>73dacc2c-8787-4799-87e0-57763c7c2a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'flow-action-select' and @type = 'text' and @placeholder = 'Select an action']</value>
      <webElementGuid>1cef1e60-b99e-456d-9031-536d821ff244</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
