<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_flow-step-name</name>
   <tag></tag>
   <elementGuidId>80853b39-1d57-467d-8349-5ecbf65c39b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flow-step-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flow-step-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c0ed8e7-84c3-4f08-a78a-72482befce3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>ed462f7d-92d6-4ecf-9d8f-9265e239ee44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flow-step-name</value>
      <webElementGuid>479de2bb-4ba5-4284-999c-3690bd11e58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2b50210-a28b-4125-8a33-9d4673df945e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a4789a92-782c-4387-87d9-9ce9b5cc88e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Step Name...</value>
      <webElementGuid>4e31b919-d55f-402b-97e8-aacc40d6613f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flow-step-name&quot;)</value>
      <webElementGuid>8690b180-35e7-4664-99af-31e696019d95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flow-step-name']</value>
      <webElementGuid>6981c1f5-e99b-45f2-85d5-a6fc083fabd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name']/div/input</value>
      <webElementGuid>40356626-b56d-4800-936b-0158f06f6430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b032e2c8-ad59-41c1-8ad7-f93137aaac2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'flow-step-name' and @type = 'text' and @placeholder = 'Step Name...']</value>
      <webElementGuid>14f8129f-f2cb-4d3c-a9ca-8b3b7e706545</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
