<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__connection-name</name>
   <tag></tag>
   <elementGuidId>d9e41199-1082-4071-85c7-0610efedbfd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connection-name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'connection-name' and @type = 'text' and @placeholder = 'Connection Name']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='connection-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>baf19470-33e4-4040-a401-a1f3e8e54625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>4f66ef92-1f7f-4549-8808-b3db8a642fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-name</value>
      <webElementGuid>c1fb875f-490b-4960-b1d3-3cb4de9cbef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d30c802-7a22-4baa-ad51-abbe1c73bf4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>48f539d1-956b-4c84-b66d-44af464689c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Connection Name</value>
      <webElementGuid>6ce80e96-37dd-4390-83d3-aa8a785b1295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-name&quot;)</value>
      <webElementGuid>25cc7f35-c9ee-42eb-a17a-7eeedd6cba98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='connection-name']</value>
      <webElementGuid>c3bada2f-5b2a-4c20-a903-c138d34c3f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-connection']/div/div[2]/div/div/div/input</value>
      <webElementGuid>469c6865-667b-48ea-b4a5-5620308b38c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>baf40fba-fc61-4876-a587-ff02b514ceb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'connection-name' and @type = 'text' and @placeholder = 'Connection Name']</value>
      <webElementGuid>175900c2-da9c-4221-82c6-e025e637bee9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
