<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__user-lastname</name>
   <tag></tag>
   <elementGuidId>6164608d-a548-4e99-aa4f-7231a6db27d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user-lastname</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'user-lastname' and @type = 'text' and @placeholder = 'Lastname']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user-lastname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2c457df-86dc-4a61-bd28-653f6b2262c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-input__inner</value>
      <webElementGuid>7fbe061b-2a84-4b2c-ad6d-2a1dee89afda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>test-id</name>
      <type>Main</type>
      <value>user-lastname</value>
      <webElementGuid>fba5ea3c-f292-4fb7-a918-698b75bb0bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-lastname</value>
      <webElementGuid>86c6bd94-d066-4021-8ce6-0a5dbfba2a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b0b51a55-146d-42e7-80c7-26e90ec96ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>063470e1-06a2-461b-9c03-2f16ac5b5515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Lastname</value>
      <webElementGuid>1c74b35f-9089-47e0-9794-314ea87fdf70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-lastname&quot;)</value>
      <webElementGuid>f826ae3d-f6d8-4639-bd95-ad42bb412b75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user-lastname']</value>
      <webElementGuid>a2da6476-c235-41d6-86c5-8c5671c4218b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit-user']/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>c8c1b8cc-0f83-4e08-98ec-cf498d1dcc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>7370e2d6-8e50-41fb-81fd-c7e0f28f44b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user-lastname' and @type = 'text' and @placeholder = 'Lastname']</value>
      <webElementGuid>c7f0e804-6bd9-4680-bdb2-dafb918642c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
