<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_4allportalConnector-v1.0</name>
   <tag></tag>
   <elementGuidId>4a64b3fc-c41f-42f5-8450-11c85e521b30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connector-spec-option-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='connector-spec-option-10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>15dc540d-d025-4796-91f2-6943ec98af39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>c95cf691-e18b-4464-abb8-2214f4e09a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connector-spec-option-10</value>
      <webElementGuid>cce19eed-a330-4369-ad0e-90bccf19f8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4allportalConnector-v1.0</value>
      <webElementGuid>345d89fa-883f-446e-85e4-b99399b123ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connector-spec-option-10&quot;)</value>
      <webElementGuid>d8bd336d-ecb9-4a31-a57a-f59281fb26a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='connector-spec-option-10']</value>
      <webElementGuid>203d2a9d-b659-4a05-a19f-2ee772d81798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-3226']/div/div/div/ul/li[11]</value>
      <webElementGuid>3cc9ac08-8dad-49fd-8631-520c78dea313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='onedriveConnector-v1.0'])[1]/following::li[1]</value>
      <webElementGuid>54f0d270-8ef5-4cac-a73b-6f5b8b8ed175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='blendConnector-v1.0'])[1]/following::li[2]</value>
      <webElementGuid>b603ca41-31fd-4021-9832-2355d5792db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='http-rest-1.0'])[1]/preceding::li[1]</value>
      <webElementGuid>f2d5c2cd-20ad-4558-bfda-b657c7f4c827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='openaiConnector-v1.0'])[1]/preceding::li[2]</value>
      <webElementGuid>b3821e56-1298-4a57-895f-6feee4110eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]</value>
      <webElementGuid>463208ac-88e0-4993-aa87-81f066917470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'connector-spec-option-10' and (text() = '4allportalConnector-v1.0' or . = '4allportalConnector-v1.0')]</value>
      <webElementGuid>afb4b3d8-d1e6-4bc4-b87b-0e9efbbff8b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
