<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_4AllPortal Connector -v1.0</name>
   <tag></tag>
   <elementGuidId>4513f03a-faf8-43bc-903f-142eb86449e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='connection-connector-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connection-connector-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e05a6cbc-70f0-4778-bd66-0cd56f37286f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>ef1ef27d-507c-451d-9afb-3bcd1b05c510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-connector-option-0</value>
      <webElementGuid>0db573e7-1c71-43f3-878a-d6251aa6a329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  4AllPortal Connector -v1.0</value>
      <webElementGuid>8aa97de0-67f0-4853-a59b-8bd4bd58bec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-connector-option-0&quot;)</value>
      <webElementGuid>dbfd4d98-3a21-4ec6-9656-83b312be325a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='connection-connector-option-0']</value>
      <webElementGuid>58a64b70-4a9e-49fd-9506-7e9562b62598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-1730']/div/div/div/ul/li</value>
      <webElementGuid>767b28fd-1d99-4907-826d-aadf6966559a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'connection-connector-option-0', '&quot;', ')')])[1]/following::li[1]</value>
      <webElementGuid>98411f04-daf2-4e58-abbb-6c188063174a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/ul/li</value>
      <webElementGuid>7c899a7e-d9d9-4ae1-b7e1-acc99138e0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'connection-connector-option-0' and (text() = '  4AllPortal Connector -v1.0' or . = '  4AllPortal Connector -v1.0')]</value>
      <webElementGuid>558c8e6b-4a23-4970-bfd0-8eca2d2357ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
