<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Akeneo Connector -v1.0</name>
   <tag></tag>
   <elementGuidId>6ca300c6-9fcd-4784-8380-a986c8f434f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='connection-connector-option-6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connection-connector-option-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e71a5db7-9e9b-4ce1-8bf8-bf538ac4f4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>7fc4bff1-c785-4b41-91b1-4492d0504338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-connector-option-6</value>
      <webElementGuid>37b91a52-2c14-48d2-bc77-207601845b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Akeneo Connector -v1.0</value>
      <webElementGuid>3ca005c3-421f-47b1-b442-b2b7657e0ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-connector-option-6&quot;)</value>
      <webElementGuid>ee4b49ae-fd89-4965-b1bf-418830e24815</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='connection-connector-option-6']</value>
      <webElementGuid>085c33af-bc55-4c3b-8c17-78aec0b9cd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-2205']/div/div/div/ul/li[7]</value>
      <webElementGuid>7faaf874-152e-4872-a413-02db131f61b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/ul/li[7]</value>
      <webElementGuid>d68faf2d-f3f4-44a7-b03a-b34f1b3869e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'connection-connector-option-6' and (text() = '  Akeneo Connector -v1.0' or . = '  Akeneo Connector -v1.0')]</value>
      <webElementGuid>c1743b2c-486e-44d8-b39a-419de1ebc9ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
