<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AWS S3 Connector -v1.0</name>
   <tag></tag>
   <elementGuidId>8bc70329-780c-4d9f-bd8a-0fa3c13b09f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connection-connector-option-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='connection-connector-option-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7ab02fc0-558b-43e1-a69e-e8286a28ccc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>1aa856cf-9e22-493f-a8f0-541a4340348c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-connector-option-8</value>
      <webElementGuid>bc0fc81d-3ea1-4c1c-8a5f-78152acccbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  AWS S3 Connector -v1.0</value>
      <webElementGuid>2ecbf722-15fb-459f-a9e1-9bb0f93f5ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-connector-option-8&quot;)</value>
      <webElementGuid>110c4d53-6cf7-4029-a515-b9c4d14ff606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='connection-connector-option-8']</value>
      <webElementGuid>8c94cef1-f69d-40f9-8b17-8743973fed21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-798']/div/div/div/ul/li[9]</value>
      <webElementGuid>4a66be0c-2b5a-4f59-b3f1-1689cb0c3171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/ul/li[9]</value>
      <webElementGuid>4ee43f5e-644e-4338-ae49-df23e73f63f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'connection-connector-option-8' and (text() = '  AWS S3 Connector -v1.0' or . = '  AWS S3 Connector -v1.0')]</value>
      <webElementGuid>e5ab1563-72e2-4cf0-ab0f-a7d5cb80cba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
