<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_agilityConnector-v1.0</name>
   <tag></tag>
   <elementGuidId>016a37b6-5d00-4d6c-a7ec-528793232b6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='connector-spec-option-41']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connector-spec-option-41</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>16b34c34-b295-4bed-b2ed-c64076a92997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>168abc28-cdca-4cb8-8315-9a66f0f21cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connector-spec-option-41</value>
      <webElementGuid>6fc908c2-1450-4e2d-91ba-35f3ae40d085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>agilityConnector-v1.0</value>
      <webElementGuid>9f396e6e-31bd-4ab6-b90b-0a19ef36aac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connector-spec-option-41&quot;)</value>
      <webElementGuid>2f930939-4c3f-4284-a289-e01a740757ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='connector-spec-option-41']</value>
      <webElementGuid>2edc384b-2824-4492-9264-de0f583728f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-2368']/div/div/div/ul/li[42]</value>
      <webElementGuid>372af743-ce9d-4f87-82b7-5213c4dccea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='drupalConnector-v1.0'])[1]/following::li[1]</value>
      <webElementGuid>9bd157c6-522d-4b6a-b7b7-3d9add7fccab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='webhookConnector-v1.0'])[1]/following::li[2]</value>
      <webElementGuid>ec824528-e11d-4fc0-a020-bc6605030e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='magentoConnector-v1.0'])[1]/preceding::li[1]</value>
      <webElementGuid>3d0df9a4-df03-439e-97a3-6438672062d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[42]</value>
      <webElementGuid>b3d09c05-4c8b-4f68-9a21-e4644ce7d729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'connector-spec-option-41' and (text() = 'agilityConnector-v1.0' or . = 'agilityConnector-v1.0')]</value>
      <webElementGuid>cc12cbfe-f707-41c8-94b6-67002a38c86a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
