<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Authorization Code</name>
   <tag></tag>
   <elementGuidId>f7a44a3c-4103-42a4-8770-8ee90b335375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-popper-3594 > div.el-select-dropdown > div.el-scrollbar > div.el-select-dropdown__wrap.el-scrollbar__wrap.el-scrollbar__wrap--hidden-default > ul.el-scrollbar__view.el-select-dropdown__list > li.el-select-dropdown__item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-popper-3594']/div/div/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>00bd869a-4c98-4e67-b75b-0801d0d5d057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>ffb38cfb-0135-4db5-806c-e3c852106ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Authorization Code</value>
      <webElementGuid>87475a9a-003b-466f-b4c9-98d0e3ffbb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-popper-3594&quot;)/div[@class=&quot;el-select-dropdown&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-select-dropdown__wrap el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/ul[@class=&quot;el-scrollbar__view el-select-dropdown__list&quot;]/li[@class=&quot;el-select-dropdown__item&quot;]</value>
      <webElementGuid>7d9b595b-bae3-4ef2-b54f-7d1308959e84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-3594']/div/div/div/ul/li</value>
      <webElementGuid>445c9a7e-59bd-4d05-b9cc-79284c316db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oauth'])[2]/following::li[1]</value>
      <webElementGuid>6ef8f292-e79e-4c5f-8a52-f37b97d33a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/ul/li</value>
      <webElementGuid>441b49a5-e9a0-40b2-b59b-a9fe623c5d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Authorization Code' or . = 'Authorization Code')]</value>
      <webElementGuid>cf240351-899a-448c-b148-b35759a07632</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
