<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Bearer</name>
   <tag></tag>
   <elementGuidId>aa765402-bb63-47c1-8482-31dccc300614</elementGuidId>
   <imagePath>../../Pictures/Katalon Screenshots/li_Bearer_customAttributes.png</imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Bearer' or . = 'Bearer')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>../../Pictures/Katalon Screenshots/li_Bearer_customAttributes.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-popper-3116']/div/div/div/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.el-select-dropdown.is-multiple > div.el-scrollbar > div.el-select-dropdown__wrap.el-scrollbar__wrap.el-scrollbar__wrap--hidden-default > ul.el-scrollbar__view.el-select-dropdown__list > li.el-select-dropdown__item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5d5b5737-82e8-4606-a6bd-539c6439dff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>6ff0cdad-da04-489d-a1d0-4b30542c6175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bearer</value>
      <webElementGuid>205f5075-c883-4350-9a54-0dac2d67dc21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-popper-3116&quot;)/div[@class=&quot;el-select-dropdown is-multiple&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-select-dropdown__wrap el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/ul[@class=&quot;el-scrollbar__view el-select-dropdown__list&quot;]/li[@class=&quot;el-select-dropdown__item&quot;]</value>
      <webElementGuid>107c1797-46a2-489e-884d-7b01c93dcc08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-3116']/div/div/div/ul/li</value>
      <webElementGuid>062445af-60ba-44a9-b6f4-d272196abec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/ul/li</value>
      <webElementGuid>4a443446-d047-4be1-82ba-c7cc8ff13d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Bearer' or . = 'Bearer')]</value>
      <webElementGuid>87e0196b-2b01-427a-9089-212e6ee29b2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
