<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_BASIC</name>
   <tag></tag>
   <elementGuidId>7ec043fd-37b5-4f76-9e4b-4f8c06f40e03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connection-authentication-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='connection-authentication-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>53ae4ed8-3898-454f-bc65-987830e273bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>60f946a1-926f-467f-8ee2-ce2e5f29815f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-authentication-option-0</value>
      <webElementGuid>6dac0322-8e5a-4c7d-93e5-13b69c1b6df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BASIC</value>
      <webElementGuid>95bc37ad-7e4f-442f-8a9e-45b8903fd249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-authentication-option-0&quot;)</value>
      <webElementGuid>3630a250-578c-41cb-adc1-72ae3cdac7fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='connection-authentication-option-0']</value>
      <webElementGuid>e6420677-908d-48fa-97ca-46e3b7326f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-6600']/div/div/div/ul/li</value>
      <webElementGuid>86e1833c-c5dc-486d-b2e3-e527d9be6d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/ul/li</value>
      <webElementGuid>c0d3c943-94fe-40f3-9b60-ea7fd764c32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'connection-authentication-option-0' and (text() = 'BASIC' or . = 'BASIC')]</value>
      <webElementGuid>93a427a1-96a9-4bde-956a-2bf8c2b60a09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
