<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Bria Connector -v1.0</name>
   <tag></tag>
   <elementGuidId>f7187179-99ff-49b7-87f0-242361bb969b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connection-connector-option-11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='connection-connector-option-11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>7009f5ce-6a44-4f4a-848c-b43f1b1973a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>7b9a33b7-fd39-4d95-ba62-5725dc4231a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-connector-option-11</value>
      <webElementGuid>a3d67660-8e66-4c96-97fa-cfa742154278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Bria Connector -v1.0</value>
      <webElementGuid>bbbd5098-f68e-472e-be47-46b08b754f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-connector-option-11&quot;)</value>
      <webElementGuid>d8f71c13-d8bc-4826-9c36-5ce2c9fea73c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='connection-connector-option-11']</value>
      <webElementGuid>ad580d73-8b37-4a41-9403-d3915837be00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-2373']/div/div/div/ul/li[12]</value>
      <webElementGuid>209ec7e3-8f10-4638-b2a2-a9c584e601b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]</value>
      <webElementGuid>bd2b8c3a-fc0e-460d-9ebd-839ad5a1b221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'connection-connector-option-11' and (text() = '  Bria Connector -v1.0' or . = '  Bria Connector -v1.0')]</value>
      <webElementGuid>920d9869-1489-47cb-8171-585738030e4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
