<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_CORE</name>
   <tag></tag>
   <elementGuidId>b71d02c6-38c8-43c4-ad1d-14933c20462e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='connector-type-option-core']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connector-type-option-core</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>27882fbb-c3ef-4460-9a8d-7888cb939bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>df4591d9-81e7-40ef-a4d4-63bf7bd31b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connector-type-option-core</value>
      <webElementGuid>1171eb4f-f1f2-4d8b-851c-888c574693a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CORE</value>
      <webElementGuid>78831fd7-5362-47a1-bf5d-73e7683e3178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connector-type-option-core&quot;)</value>
      <webElementGuid>ac075e4f-b914-4f85-9aac-f1ea6993de25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='connector-type-option-core']</value>
      <webElementGuid>dbbd581d-3209-4682-ac75-0f5780d040e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-1492']/div/div/div/ul/li</value>
      <webElementGuid>f9e98ae4-0c45-4be0-9185-d0c855927d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='showpadConnector-v1.0'])[1]/following::li[1]</value>
      <webElementGuid>df8c5a96-7f3f-49cb-85bf-e6325a701afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='inRiverConnector-v1.0'])[1]/following::li[2]</value>
      <webElementGuid>1ce97d24-c1a8-4566-980c-a05f9679bb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTERNAL'])[1]/preceding::li[1]</value>
      <webElementGuid>05a5fcf4-aa85-4d29-b169-23eb64234117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/ul/li</value>
      <webElementGuid>627c9f3e-4bd0-4855-8929-40386ccca9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'connector-type-option-core' and (text() = 'CORE' or . = 'CORE')]</value>
      <webElementGuid>38a1a8cd-8a58-4019-8f9e-d641bbc49c26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
