<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Connections</name>
   <tag></tag>
   <elementGuidId>376571cc-f42c-4297-9069-23ed8d06a3d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-connections</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-connections']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>52e4c157-ae9b-4e0c-b45a-88eff7cf5344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-menu-item font-size</value>
      <webElementGuid>38d1fc4f-d486-4a6b-a533-f22a73562ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>ba9e7949-d051-4c63-b9a9-0919a7950cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b37d3952-6e6d-456a-bb76-459a73e52400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-connections</value>
      <webElementGuid>d9059e6a-9aa6-43e7-bc80-fb5a3266d78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connections</value>
      <webElementGuid>61de9f69-d2ab-4270-af33-db56b0c1c488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-connections&quot;)</value>
      <webElementGuid>66234704-05c6-44f9-8f68-8b9eefc73fac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='menu-connections']</value>
      <webElementGuid>b9663211-f298-4569-98bb-40d03e7709b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-nav']/ul/li[4]</value>
      <webElementGuid>d9f7304a-2938-4ca9-a726-f5b6f2e6ad95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activities'])[1]/following::li[1]</value>
      <webElementGuid>80a054c3-9cef-48dd-b570-7e32831729cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flows'])[1]/following::li[2]</value>
      <webElementGuid>823e3e0a-68ca-4e1d-844a-f74de1cf8a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connectors'])[1]/preceding::li[1]</value>
      <webElementGuid>2f554f1e-029a-45e7-9791-156d6cb28cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]</value>
      <webElementGuid>62311532-5e3f-47b1-bd19-cec2670b0e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'menu-connections' and (text() = 'Connections' or . = 'Connections')]</value>
      <webElementGuid>dbf6bcdf-9111-440d-8e84-657564a9d94e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
