<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Dashboard</name>
   <tag></tag>
   <elementGuidId>6be72ea0-4289-4673-8e1c-0af29161dfa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-dashboard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-dashboard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>65e15de0-3d82-4adf-83a5-584641781b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-menu-item font-size</value>
      <webElementGuid>35144b89-496e-4b78-818c-eccebf5c2fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>c5823463-bc59-4619-ac7d-11cc3a55e345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f7436906-9955-453e-a4f9-79871f287e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-dashboard</value>
      <webElementGuid>22c71ea3-eb19-4302-af59-f6715c584d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>0eebbfa1-b74a-4e59-959d-abdf17749204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-dashboard&quot;)</value>
      <webElementGuid>c0973060-a085-4506-942c-bf845b556224</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='menu-dashboard']</value>
      <webElementGuid>79f5f949-6914-4cb9-8b33-4e05f9fa9c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebar-nav']/ul/li</value>
      <webElementGuid>d1c6fb75-40a1-442b-912c-3cf2b0c14be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flows'])[1]/preceding::li[1]</value>
      <webElementGuid>ffe4fc66-226e-4a14-9ae9-4ccbf50656a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>898784af-e052-4df0-b0ba-037e38124639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'menu-dashboard' and (text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>81ef2c2c-1eeb-4677-ae6a-3dabd6599bc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
