<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Dropbox Connector -v1.0</name>
   <tag></tag>
   <elementGuidId>bd091d4b-bdc2-479e-82ed-f9fc16f63dc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connection-connector-option-17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='connection-connector-option-17']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>eceffbde-49af-4862-a112-99180cc870d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>02c554c8-34f4-4250-982c-bc71193dd1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connection-connector-option-17</value>
      <webElementGuid>ffd1d78f-e1e2-4465-b920-fa737fbe7b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Dropbox Connector -v1.0</value>
      <webElementGuid>cd792554-2970-4736-83bd-0cad1d686a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connection-connector-option-17&quot;)</value>
      <webElementGuid>d73c1141-9542-477e-8cbc-700aeef62385</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='connection-connector-option-17']</value>
      <webElementGuid>4e5c046f-4d47-41fa-b8ca-9c1521ebbe22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-5216']/div/div/div/ul/li[18]</value>
      <webElementGuid>6ad59e7f-567d-432a-acba-ead61f63c255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[18]</value>
      <webElementGuid>f5919761-4351-452f-b731-0ec8def84a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'connection-connector-option-17' and (text() = '  Dropbox Connector -v1.0' or . = '  Dropbox Connector -v1.0')]</value>
      <webElementGuid>718f331d-0915-4232-b186-a2e43fa9f8f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
