<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Get Items</name>
   <tag></tag>
   <elementGuidId>281dd9ee-beda-4ccb-a5f7-54333ccab67c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='flow-action-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flow-action-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>de986626-d780-4c94-a9f2-029e6847c9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item scrollable-tooltip</value>
      <webElementGuid>9c743264-22c2-4e7f-96d5-db8b403966c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flow-action-option-0</value>
      <webElementGuid>00ea26a2-5b08-40f2-8def-2f75407eeb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>756e61da-3fea-46ce-bb61-8262a62c8528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>el-popper-6490</value>
      <webElementGuid>e87ff985-313d-4630-a464-fcd29799f725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Items</value>
      <webElementGuid>a23ab1c0-bb2e-4b38-8801-018f3cc17100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flow-action-option-0&quot;)</value>
      <webElementGuid>d8fa2464-425e-4f3e-85c2-960b27524ae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='flow-action-option-0']</value>
      <webElementGuid>cf749676-7d17-41f3-846a-e6b44579d9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-8977']/div/div/div/ul/div/li</value>
      <webElementGuid>9f4b2c2c-2e94-4a3d-bd15-a07105dda25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prime'])[1]/following::li[2]</value>
      <webElementGuid>6b61b88c-51f0-4145-a3f7-c46c35a9b60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Item'])[1]/preceding::li[1]</value>
      <webElementGuid>e578033b-0842-44c6-bf7d-b13d6f140b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li</value>
      <webElementGuid>d155455c-c556-494d-83fd-a38e39bbb689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'flow-action-option-0' and (text() = 'Get Items' or . = 'Get Items')]</value>
      <webElementGuid>aa060103-08fe-457b-bfb7-d332f5a837dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
