<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Oauth</name>
   <tag></tag>
   <elementGuidId>6a032e88-1b6e-41b7-be30-9e32a15d2bc6</elementGuidId>
   <imagePath>../../Pictures/Katalon Screenshots/li_outh.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>../../Pictures/Katalon Screenshots/li_outh.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.el-select-dropdown.is-multiple > div.el-scrollbar > div.el-select-dropdown__wrap.el-scrollbar__wrap.el-scrollbar__wrap--hidden-default > ul.el-scrollbar__view.el-select-dropdown__list > li.el-select-dropdown__item</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Oauth' or . = 'Oauth')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-popper-6069']/div/div/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5edb613e-52d5-48c4-ba78-26de0ce0fbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>3ad2375b-4ceb-4bee-94ee-105a1223b8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oauth</value>
      <webElementGuid>9178adb5-5e5c-43dd-85e0-a589ae968f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-popper-6069&quot;)/div[@class=&quot;el-select-dropdown is-multiple&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-select-dropdown__wrap el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/ul[@class=&quot;el-scrollbar__view el-select-dropdown__list&quot;]/li[@class=&quot;el-select-dropdown__item&quot;]</value>
      <webElementGuid>a365c1f0-84c6-4260-8129-930e039edaaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-6069']/div/div/div/ul/li</value>
      <webElementGuid>21e72475-c902-4884-96a4-5b90d0a850b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/ul/li</value>
      <webElementGuid>bdb55b30-4758-4969-a17a-592d4d432aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Oauth' or . = 'Oauth')]</value>
      <webElementGuid>4751c68e-9ba0-4b8c-aec4-92008d78cb58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
