<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Product uuid Get a product (GET)</name>
   <tag></tag>
   <elementGuidId>9bf32a1d-4a04-4f4e-a30b-20f34c3c90cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='flow-action-option-105']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flow-action-option-105</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>39a028b5-bd1e-4965-86ec-d604fd037c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item scrollable-tooltip</value>
      <webElementGuid>f9a40f6c-e76a-44d7-91d5-d8e43b7a6592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flow-action-option-105</value>
      <webElementGuid>0bcf59ca-06f6-45ab-9516-04497abcad4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>68200e21-2436-4d5e-9dfb-8328ef20242e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>el-popper-4892</value>
      <webElementGuid>e139091c-9fb6-4683-8572-11ab670d6b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product [uuid]: Get a product (GET)</value>
      <webElementGuid>786d0c55-dde3-46d5-b8c2-763fc382b031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flow-action-option-105&quot;)</value>
      <webElementGuid>0e6b4406-7484-47e1-94eb-3e8b976117e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='flow-action-option-105']</value>
      <webElementGuid>77e753d2-4128-4d30-8c6b-28cb1ba4e267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-2187']/div/div/div/ul/div[106]/li</value>
      <webElementGuid>d53a18d6-7069-4c47-af1e-aaca26925c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product [uuid]: Get a draft (GET)'])[1]/following::li[1]</value>
      <webElementGuid>df5a9034-ee63-4b4e-ad74-b6a4fa13ed78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product [uuid]: Delete a product (DELETE)'])[1]/following::li[2]</value>
      <webElementGuid>eb4960c3-0680-4c8e-a019-c929140f9bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product [uuid]: Get list of products (GET)'])[1]/preceding::li[1]</value>
      <webElementGuid>2620f2f6-8eb5-4eb8-9b39-2b84b95044e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[106]/li</value>
      <webElementGuid>cf646510-b42a-473d-ad3b-714178649a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'flow-action-option-105' and (text() = 'Product [uuid]: Get a product (GET)' or . = 'Product [uuid]: Get a product (GET)')]</value>
      <webElementGuid>a4681a24-ac52-4da9-8edf-a8a579d3fc22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
