<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_PAID</name>
   <tag></tag>
   <elementGuidId>c1ca01d8-9775-4036-8066-ae1f0f6dc13a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='connector-pricing-option-paid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#connector-pricing-option-paid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>29e005da-a93b-443d-bfb0-9a534761b054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>e30ea908-1814-4e48-b7f4-1fcadf054136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>connector-pricing-option-paid</value>
      <webElementGuid>e7143f2e-1a4e-4db1-8668-b5104f77635b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAID</value>
      <webElementGuid>03f33338-5195-40c7-be1b-fdd986b4c371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connector-pricing-option-paid&quot;)</value>
      <webElementGuid>6dacf855-284b-4ce6-880e-3ba7c751caa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='connector-pricing-option-paid']</value>
      <webElementGuid>1b36a94e-47b1-4924-8f43-b19941e4c402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-1583']/div/div/div/ul/li[2]</value>
      <webElementGuid>dee14793-2440-4d08-a1cd-4d1f2e8043c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FREE'])[1]/following::li[1]</value>
      <webElementGuid>214ed3b3-c167-459e-9056-26c6afb6ce1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTERNAL'])[1]/following::li[2]</value>
      <webElementGuid>b6ac85c2-de15-4267-b081-63ebcb673de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/ul/li[2]</value>
      <webElementGuid>c3c34da0-6ef6-4286-a222-5858e3adaa8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'connector-pricing-option-paid' and (text() = 'PAID' or . = 'PAID')]</value>
      <webElementGuid>38b5c302-799e-4c7e-9ad7-32d1e90f370e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
