<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_ROLE_ADMIN</name>
   <tag></tag>
   <elementGuidId>5baa7325-b1a5-40a5-8516-4470c07039ce</elementGuidId>
   <imagePath>../../Pictures/Katalon Screenshots/Matched Elements/role_admin.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>../../Pictures/Katalon Screenshots/Matched Elements/role_admin.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;el-popper-8094&quot;)/div[@class=&quot;el-select-dropdown&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-select-dropdown__wrap el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/ul[@class=&quot;el-scrollbar__view el-select-dropdown__list&quot;]/li[@class=&quot;el-select-dropdown__item&quot;][count(. | //li[@class = 'el-select-dropdown__item' and (text() = 'ROLE_ADMIN' or . = 'ROLE_ADMIN')]) = count(//li[@class = 'el-select-dropdown__item' and (text() = 'ROLE_ADMIN' or . = 'ROLE_ADMIN')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='el-popper-7603']/div/div/div/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d0893ce5-b75c-4815-88f4-c627228f78dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>594e0fc1-1833-4d5d-8ed7-c80d8ec2067b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ROLE_ADMIN</value>
      <webElementGuid>a4d4eb91-12c1-498c-a9f3-04cd0a782562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-popper-7603&quot;)/div[@class=&quot;el-select-dropdown&quot;]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-select-dropdown__wrap el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/ul[@class=&quot;el-scrollbar__view el-select-dropdown__list&quot;]/li[@class=&quot;el-select-dropdown__item&quot;]</value>
      <webElementGuid>42bcafa7-232d-4cd1-8ba6-b3ab01587d48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-7603']/div/div/div/ul/li[2]</value>
      <webElementGuid>0376124e-51fe-41a3-b59c-e76c1e3ba2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROLE_STAFF'])[1]/following::li[1]</value>
      <webElementGuid>578fbe44-ee23-42a5-8090-7b74606041d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[2]/following::li[2]</value>
      <webElementGuid>ac0b89e4-a4c1-449b-8b82-a1b86c10b5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROLE_USER'])[1]/preceding::li[1]</value>
      <webElementGuid>8dbe8747-088a-41d6-bba3-86113ef75c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/ul/li[2]</value>
      <webElementGuid>b7c5bbe5-8bf3-415e-b22f-d636b898bcf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'ROLE_ADMIN' or . = 'ROLE_ADMIN')]</value>
      <webElementGuid>2731a1c4-9844-4cac-82f6-d1cfffd69d71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
