<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Search Files On Dropbox_1</name>
   <tag></tag>
   <elementGuidId>442a781e-637a-46f0-acb2-95350f2164e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='flow-body-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flow-body-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>46c918f2-a995-4aec-9035-ff4763befb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>adf3ff3a-8a7b-4e42-b1e0-e8f9006c3894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flow-body-option-0</value>
      <webElementGuid>81b13c9f-0926-4974-b0ab-c7ef8affc434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search Files On Dropbox</value>
      <webElementGuid>4e47837f-0f36-497c-a20d-b2ac0e9245f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flow-body-option-0&quot;)</value>
      <webElementGuid>6218bbc6-223a-4bfe-9797-2203b32e4a00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='flow-body-option-0']</value>
      <webElementGuid>c06b06c5-e105-4b95-8791-127cc5306a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-9644']/div/div/div/ul/li</value>
      <webElementGuid>903fdef6-20e5-4edf-8ebf-a93a810c7220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Files On Dropbox'])[2]/following::li[1]</value>
      <webElementGuid>cd1fbc89-e209-4afb-bf06-2d22c985d901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move Files On Dropbox'])[2]/following::li[1]</value>
      <webElementGuid>d9695125-dc68-4c5e-ad0b-eac55f183a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div/div/ul/li</value>
      <webElementGuid>e61f5689-ad79-43a3-a552-95d21f14a109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'flow-body-option-0' and (text() = 'Search Files On Dropbox' or . = 'Search Files On Dropbox')]</value>
      <webElementGuid>ec551305-cf61-4da3-b702-156bbbad7d37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
