<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Search Files On Dropbox</name>
   <tag></tag>
   <elementGuidId>7006387f-2472-4e4b-a40e-184d722dd056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='flow-action-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flow-action-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d043f439-1dd9-4999-bf8a-0068b827de03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item scrollable-tooltip</value>
      <webElementGuid>2fbb1144-4ce4-41c5-9de8-c1a0700988a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flow-action-option-0</value>
      <webElementGuid>51f191f4-6a01-46ed-8846-c78e73f73c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c09c8de4-93e3-449f-a5b4-01ba24391dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>el-popper-4008</value>
      <webElementGuid>f2a26bee-de60-49f5-aee8-9da6c30376a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search Files On Dropbox</value>
      <webElementGuid>77a2d933-0cab-4497-a707-e6a1277cfcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flow-action-option-0&quot;)</value>
      <webElementGuid>92622c94-d555-47cf-be06-9d6bfd2a9170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='flow-action-option-0']</value>
      <webElementGuid>eb4f7c11-bb53-487d-a39e-c02d5727b52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-2511']/div/div/div/ul/div/li</value>
      <webElementGuid>4b3fb00f-36d2-43f9-b7bb-5884a9222ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prime'])[1]/following::li[2]</value>
      <webElementGuid>891e308a-b37e-43f4-af03-781ac9f51e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Files On Dropbox'])[1]/preceding::li[1]</value>
      <webElementGuid>379f89fa-2bdb-4013-bd66-0a9f2ece3029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li</value>
      <webElementGuid>371b7591-fd8f-4ea8-8cff-85c588f0a001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'flow-action-option-0' and (text() = 'Search Files On Dropbox' or . = 'Search Files On Dropbox')]</value>
      <webElementGuid>75eff4f6-5630-4be4-9109-8e6ff36cbffc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
