<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Search Search for images matching the gi_c65525</name>
   <tag></tag>
   <elementGuidId>5369de36-5dcb-451f-82ba-74b98dcaf8fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flow-action-option-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='flow-action-option-14']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>27e3db9b-b99c-4a5d-8df4-75e5ab73fa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item scrollable-tooltip</value>
      <webElementGuid>6d201e95-6efa-48f7-82a6-b8093d08e33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flow-action-option-14</value>
      <webElementGuid>cd73e1b8-5e1d-414c-bdce-6df7e0b85358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>092d48ad-a9d1-48fe-9213-a24ea0f5b49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>el-popper-9878</value>
      <webElementGuid>1e99b88b-0023-46e1-91a0-30b6b696912a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search: Search for images matching the given text query (GET)</value>
      <webElementGuid>2cb06d41-3063-464f-bad6-cf1c5d28341c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flow-action-option-14&quot;)</value>
      <webElementGuid>a5b6fd27-58e6-4e83-8899-efedb551ed2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='flow-action-option-14']</value>
      <webElementGuid>47858bc5-8ff1-4abd-b67f-ce727cff3dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-436']/div/div/div/ul/div[15]/li</value>
      <webElementGuid>88b97a3d-cbf3-40ff-ad1e-2f3d63d0903f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Replace_bg: Replace the background of an image (POST)'])[1]/following::li[1]</value>
      <webElementGuid>893f178e-ab21-4d9a-9558-14b1c019c1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove_bg: Remove the background of an image (GET)'])[1]/following::li[2]</value>
      <webElementGuid>659d2b46-85c1-4525-be96-c8987db4b2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search_similar_images: Search for images matching the given image (GET)'])[1]/preceding::li[1]</value>
      <webElementGuid>15361b9a-f049-4c8d-a4f6-5bae89fcf0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/li</value>
      <webElementGuid>49f00d48-7ddf-468d-8218-7fea3555af4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'flow-action-option-14' and (text() = 'Search: Search for images matching the given text query (GET)' or . = 'Search: Search for images matching the given text query (GET)')]</value>
      <webElementGuid>18abb8e6-c87f-4a1c-974c-81b3b839059f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
