<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Trke</name>
   <tag></tag>
   <elementGuidId>be61765d-3d4b-4610-b6f2-568ad030c392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='login-tr-option']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-tr-option</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ff225075-3b96-459c-9296-db9b59104ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-select-dropdown__item</value>
      <webElementGuid>937b0cb0-6ed5-4826-97cf-0f40613ae8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-tr-option</value>
      <webElementGuid>ee1d01e6-5ceb-4433-b71f-bfcdc8449282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Türkçe</value>
      <webElementGuid>2bbda688-76d1-4fa2-9c1d-547678e5a3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-tr-option&quot;)</value>
      <webElementGuid>4528d8fb-ae89-4dac-8f07-9496e05730f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='login-tr-option']</value>
      <webElementGuid>7a2dff7a-7555-4003-a08d-64de5fcccc3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='el-popper-1574']/div/div/div/ul/li[2]</value>
      <webElementGuid>5a42c1ab-d6e6-437e-a2ee-129e895d453d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::li[1]</value>
      <webElementGuid>decd10d9-c5ff-4a24-ac68-58f2c7ab0293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'login-tr-option', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>786eefc1-40f0-44b7-92db-cf21927f31df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>a7930b14-288f-4a3f-802a-e728b12a38ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'login-tr-option' and (text() = 'Türkçe' or . = 'Türkçe')]</value>
      <webElementGuid>d7888484-328d-4ea1-84c3-a96de81ab888</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
