<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_112751.808 main INFO  i.c.c.c.g.i.routes._de9a31</name>
   <tag></tag>
   <elementGuidId>75f63133-b390-4ea4-a5a6-47a64a68edba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-screen']/div/p[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>68a18a80-1fa9-44c2-baa1-a5f9d0a483c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm-start</value>
      <webElementGuid>273d2463-35b5-4d97-9e98-fef06d949254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11:27:51.808 [main] INFO  i.c.c.c.g.i.routes.StepRouteBuilder - Process completed ...
</value>
      <webElementGuid>84eb2c8a-3b4a-4cb6-a561-3628b6bfb9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-step-box&quot;)/div[@class=&quot;card card-drawer background-fb oneteg-drawer-medium&quot;]/div[4]/div[@class=&quot;vdr inactive&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;modal-container&quot;]/div[2]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/div[@class=&quot;el-scrollbar__view&quot;]/div[@id=&quot;main-screen&quot;]/div[1]/p[@class=&quot;text-sm-start&quot;]</value>
      <webElementGuid>28eab87e-0a78-433b-bd30-6a4905a31c1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-screen']/div/p[9]</value>
      <webElementGuid>f58c61f5-35d1-43a0-a526-4a0ce95887c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process Logs'])[1]/following::p[9]</value>
      <webElementGuid>99d9babb-4a87-4068-a2f5-eac5f4f9ab59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step Functions'])[1]/following::p[9]</value>
      <webElementGuid>5b8d66de-bd53-416e-8aea-df7a80ecf7e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='f'])[4]/preceding::p[1]</value>
      <webElementGuid>cd8f8ca4-a536-4938-86b9-b4d0f2ece89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[9]</value>
      <webElementGuid>d00230c2-f5d1-4a5b-8338-7753a871d47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '11:27:51.808 [main] INFO  i.c.c.c.g.i.routes.StepRouteBuilder - Process completed ...
' or . = '11:27:51.808 [main] INFO  i.c.c.c.g.i.routes.StepRouteBuilder - Process completed ...
')]</value>
      <webElementGuid>eccb9b56-3b01-4324-8ced-4f323308072d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
