<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_113058.492 main INFO  i.c.c.c.g.i.routes._8a668f</name>
   <tag></tag>
   <elementGuidId>9db89f98-c74b-4631-a61f-66d86dfdac0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-screen']/div/p[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8fa28e9e-2640-4147-abde-44d9601cefe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm-start</value>
      <webElementGuid>ee262b8f-f1f0-425a-9416-e37378c59e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11:30:58.492 [main] INFO  i.c.c.c.g.i.routes.StepRouteBuilder - Process completed ...
</value>
      <webElementGuid>98073932-1891-4a3d-9e86-8cbafe3ffa3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-screen&quot;)/div[1]/p[@class=&quot;text-sm-start&quot;]</value>
      <webElementGuid>645fed6d-7b20-4a63-82eb-8406e40527e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-screen']/div/p[5]</value>
      <webElementGuid>cbb142a1-d888-4088-a67f-0eb8a44c13a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process Logs'])[1]/following::p[5]</value>
      <webElementGuid>e0094e16-dc96-4aaa-a196-13e3ea43f359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step Functions'])[1]/following::p[5]</value>
      <webElementGuid>809c8541-59b3-4017-bf3d-016740cc88d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='f'])[1]/preceding::p[1]</value>
      <webElementGuid>e81faa23-a2f8-4e1f-9607-28f13fac30ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]</value>
      <webElementGuid>bfd98785-a957-4bb1-9e21-bcacfc5dd6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '11:30:58.492 [main] INFO  i.c.c.c.g.i.routes.StepRouteBuilder - Process completed ...
' or . = '11:30:58.492 [main] INFO  i.c.c.c.g.i.routes.StepRouteBuilder - Process completed ...
')]</value>
      <webElementGuid>0fd6059b-93e9-4ff6-9a4e-9ce36c7da50d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
