<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_113639.572 main INFO  i.c.c.c.g.i.routes._c52a55</name>
   <tag></tag>
   <elementGuidId>0fdd65ad-8dba-4548-9cbd-bca7e9ba2355</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-screen']/div/p[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7271b77d-c11c-4402-886c-507f8bfebe09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm-start</value>
      <webElementGuid>e4c88cd5-39c0-4376-9920-c640c79fae73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11:36:39.572 [main] INFO  i.c.c.c.g.i.routes.StepRouteBuilder - Process completed ...
</value>
      <webElementGuid>42483800-9e17-4806-a7b1-db8b89aaa6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit-step-box&quot;)/div[@class=&quot;card card-drawer background-fb oneteg-drawer-medium&quot;]/div[4]/div[@class=&quot;vdr inactive&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;modal-container&quot;]/div[2]/div[@class=&quot;el-scrollbar&quot;]/div[@class=&quot;el-scrollbar__wrap el-scrollbar__wrap--hidden-default&quot;]/div[@class=&quot;el-scrollbar__view&quot;]/div[@id=&quot;main-screen&quot;]/div[1]/p[@class=&quot;text-sm-start&quot;]</value>
      <webElementGuid>48b751c7-f4a7-4256-943c-1a540605b4ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-screen']/div/p[9]</value>
      <webElementGuid>7d32073b-d980-4ec7-9908-0696f4ef626c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process Logs'])[1]/following::p[9]</value>
      <webElementGuid>692eaa66-df16-4542-a03e-3256b605e580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step Functions'])[1]/following::p[9]</value>
      <webElementGuid>3eb8fd60-6650-47cf-80a0-25574c5dec44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='f'])[10]/preceding::p[1]</value>
      <webElementGuid>a6668352-d101-40e7-9d2f-e2d0e8f291b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[9]</value>
      <webElementGuid>b813f729-ee9a-40d2-b5c7-fda57ba25eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '11:36:39.572 [main] INFO  i.c.c.c.g.i.routes.StepRouteBuilder - Process completed ...
' or . = '11:36:39.572 [main] INFO  i.c.c.c.g.i.routes.StepRouteBuilder - Process completed ...
')]</value>
      <webElementGuid>74751c22-cdd8-43d9-8cf1-f5aaa09d5b1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
