<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Atmosphere_propertiesqueryParamatmos_1b8258</name>
   <tag></tag>
   <elementGuidId>206b5959-62d6-486b-97b2-6f9e91549525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='#/properties/queryParam:atmosphere-select']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9bbe14fd-edc3-42e8-b7d2-1a6f27d09ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>#/properties/queryParam:atmosphere-select</value>
      <webElementGuid>e9ebd2ee-3906-44fa-9c8c-66b70c3ad5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select form-select small-input-field</value>
      <webElementGuid>7e3b5dea-35ac-4473-a0e0-63ee38aeccbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;#/properties/queryParam:atmosphere-select&quot;)</value>
      <webElementGuid>a33da130-2731-468c-aa0c-5b17064d5595</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='#/properties/queryParam:atmosphere-select']</value>
      <webElementGuid>645f445b-b27e-4b5d-8095-c27197361ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='action-form-wrapper']/div/div[12]/div/div/select</value>
      <webElementGuid>59c4a053-3488-47a5-972e-f0a7103eb09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atmosphere'])[1]/following::select[1]</value>
      <webElementGuid>84194960-18ed-44ac-8a0a-0c6e81bfef51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Synchronous'])[1]/following::select[1]</value>
      <webElementGuid>28031869-dcc0-48c1-9b39-cef01187785c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Synthetic Search'])[1]/preceding::select[1]</value>
      <webElementGuid>a5e37776-c7dd-49dd-a9b9-61b78abdfb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gallery Search'])[1]/preceding::select[1]</value>
      <webElementGuid>7be4d095-522c-432f-856b-5980e67944f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/select</value>
      <webElementGuid>40eaaa31-b070-4bf6-b3a8-083d16b543b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '#/properties/queryParam:atmosphere-select']</value>
      <webElementGuid>d548043c-03f3-48a9-b674-d2b35c5ba20c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
