<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Connectors</name>
   <tag></tag>
   <elementGuidId>c197ed0b-6c8f-450c-bec9-430944cb613b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-connectors > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-connectors']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6e500a9a-5762-4d8c-b57f-3ad39cbf4a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connectors</value>
      <webElementGuid>bc688946-ea4d-4516-8ec7-f7f438097c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-connectors&quot;)/span[1]</value>
      <webElementGuid>bc828c44-745b-4566-b6b2-d0fa21485ca6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-connectors']/span</value>
      <webElementGuid>c76e9e19-0a63-4ae4-82bf-9256f66338e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenants'])[1]/following::span[1]</value>
      <webElementGuid>c4e56d5d-61e7-4a68-9f39-ea19d9a6ce7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurations'])[1]/preceding::span[1]</value>
      <webElementGuid>e7e5658a-5e00-4292-87ed-20b278437073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privileges'])[1]/preceding::span[2]</value>
      <webElementGuid>0dc76afd-116f-4aca-8fc2-0cb4e90b005b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Connectors']/parent::*</value>
      <webElementGuid>24c2a236-8dc3-41ed-bd9c-45b6f78c21db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>d5d7c7ab-e10a-487f-b959-7258f14d115b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Connectors' or . = 'Connectors')]</value>
      <webElementGuid>54511074-e279-473a-8f9a-2bbc86fcddff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
