<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Connections</name>
   <tag></tag>
   <elementGuidId>d689ac40-f7a4-4d48-97a3-1fbe4b0c2b02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-connections > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-connections']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f1fb0f7f-6700-4e5a-b14d-8f42d7f6ae4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Connections</value>
      <webElementGuid>4cabf5e8-5ef2-4199-81d0-58e9f9e6d260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-connections&quot;)/span[1]</value>
      <webElementGuid>89aef9c9-7905-4d62-8a76-c62a91ed49ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-connections']/span</value>
      <webElementGuid>465c9666-356f-4654-96c7-abc91a3c3e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activities'])[1]/following::span[1]</value>
      <webElementGuid>2888ba0c-c850-481d-874e-3efb650774f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flows'])[1]/following::span[2]</value>
      <webElementGuid>925f27f6-5cca-4ca7-9ab4-d51d5c25debf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connectors'])[1]/preceding::span[1]</value>
      <webElementGuid>030b2cf3-c1a0-4e4e-b2be-bd8eb811b33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/preceding::span[2]</value>
      <webElementGuid>c3a2b69a-ea37-4597-9d4a-d04d5923ffa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Connections']/parent::*</value>
      <webElementGuid>2123661d-e3a8-4103-8832-985d3a1faa8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/span</value>
      <webElementGuid>96bdf17e-b166-4b4f-8113-4e16bebbeb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Connections' or . = 'Connections')]</value>
      <webElementGuid>b3821c8f-0c92-4110-b289-90d01cf43757</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
