<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PAID</name>
   <tag></tag>
   <elementGuidId>98ed835c-94e0-4d59-83ef-e20c6aa91b81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#connector-pricing-option-paid > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='connector-pricing-option-paid']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fbced5d0-c4a3-4dec-b830-65e9b6ff1a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAID</value>
      <webElementGuid>3bc29aac-92eb-437c-9b2f-a6ac912c8ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;connector-pricing-option-paid&quot;)/span[1]</value>
      <webElementGuid>09b5c192-b11c-4749-be75-5fb8eafdbff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='connector-pricing-option-paid']/span</value>
      <webElementGuid>1fba89d4-8045-42cf-877e-ff59c3ac26a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FREE'])[1]/following::span[1]</value>
      <webElementGuid>be3e6c5a-e46c-4157-9a15-5d38a3baf382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXTERNAL'])[1]/following::span[2]</value>
      <webElementGuid>388e1703-777c-48ba-9134-017772f3853e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAID']/parent::*</value>
      <webElementGuid>247068ef-da0b-4847-af9b-5437780f8267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/ul/li[2]/span</value>
      <webElementGuid>9435bb8d-4248-407c-a201-128e12fb3fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PAID' or . = 'PAID')]</value>
      <webElementGuid>f30443d4-5039-452d-a439-305bbb32fbf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
