<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_4Allportal Hospital_test_intern</name>
   <tag></tag>
   <elementGuidId>f28d6e61-0b3b-4f3b-81ee-50342b08ad12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-label0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//strong[@id='name-label0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>1b7c81f3-4cb0-4154-998f-d00c58815206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-label0</value>
      <webElementGuid>8bc4a731-707b-469c-97ba-7575381d93dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4Allportal Hospital_test_intern</value>
      <webElementGuid>5a0aef79-48f0-4eba-b22b-c9d0a868226e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-label0&quot;)</value>
      <webElementGuid>1e304572-a15a-4889-bd93-5ad4b5c38306</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//strong[@id='name-label0']</value>
      <webElementGuid>f336a152-23f7-4d63-ab1d-497593c0d794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name-0']/strong</value>
      <webElementGuid>5dae80a3-f761-4e4e-8454-a415895a3319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authentication'])[1]/following::strong[1]</value>
      <webElementGuid>ac475ce6-0c15-4a50-a41c-73afa6da1eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connector'])[1]/following::strong[1]</value>
      <webElementGuid>ae0f3163-9a00-417f-a8fb-2d16a8e60baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spotify new'])[1]/preceding::strong[1]</value>
      <webElementGuid>9318122b-0244-4e52-82fb-13eb16b32dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spotify Check Client Id'])[1]/preceding::strong[2]</value>
      <webElementGuid>0eb347a5-6b34-4c0d-af15-4c52c43ee27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4Allportal Hospital_test_intern']/parent::*</value>
      <webElementGuid>7faa20b8-a82d-4a88-b09d-ec516cf5ec09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>8e3b4c8e-659d-4e93-8675-cf9397b5c11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[@id = 'name-label0' and (text() = '4Allportal Hospital_test_intern' or . = '4Allportal Hospital_test_intern')]</value>
      <webElementGuid>7594d7ef-4a33-4efb-8f9c-c9fc20df97d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
