<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_CYANGATE</name>
   <tag></tag>
   <elementGuidId>1d92db01-11e6-4330-bbbc-c4a34760bc28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-label-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//strong[@id='name-label-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>f4e5a935-c821-4efe-9fae-1de204e88594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-label-0</value>
      <webElementGuid>aab9d4d2-eeb0-484b-9ffe-fbd615fb7c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CYANGATE</value>
      <webElementGuid>ce59d0e9-d633-4ff4-b000-b3a0b07d9241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-label-0&quot;)</value>
      <webElementGuid>fad5d6db-ffbb-4123-8a4f-7954960d4b39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//strong[@id='name-label-0']</value>
      <webElementGuid>cc65a599-e031-4412-be4e-a129af363d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name-0']/strong</value>
      <webElementGuid>b1abcdf2-d8e5-4ff3-bd5e-2eeb5d78fc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::strong[1]</value>
      <webElementGuid>1e7f33f5-4e59-4cc0-9b73-8e85e127c4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created At'])[1]/following::strong[1]</value>
      <webElementGuid>62b787f7-4648-4333-8ab5-6e6ec6bbc5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'name-label-0', '&quot;', ')')])[1]/preceding::strong[1]</value>
      <webElementGuid>07d65f19-6f8a-47fc-acbc-5ce2c617ff13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>5bb5750f-e9f1-42c1-bdd4-3d307874838c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[@id = 'name-label-0' and (text() = 'CYANGATE' or . = 'CYANGATE')]</value>
      <webElementGuid>8c892073-0a75-4fb9-8d17-c25b1e9211e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
