<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Bria Connection Katalon Test</name>
   <tag></tag>
   <elementGuidId>12dff6e3-3039-495a-ac0f-35e9588a9a24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.el-table_2_column_6.el-table__cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='show-connections']/div/div/div/div[3]/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b69cce24-906a-4c31-82e4-5031e34b72de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-table_2_column_6   el-table__cell</value>
      <webElementGuid>e049da5a-4bc2-4007-a162-2cb84d153fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rowspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7fb78a83-dd3d-4925-a25b-4cc35da8302c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>580ea6a5-febb-4262-a1b7-9a6cdf09121a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bria Connection Katalon Test</value>
      <webElementGuid>35b0325e-3fb3-42e3-9a7a-b9b2619f2f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-connections&quot;)/div[@class=&quot;el-card is-always-shadow card border-0&quot;]/div[@class=&quot;el-card__body&quot;]/div[@class=&quot;el-table--fit el-table--scrollable-y el-table--enable-row-hover el-table--enable-row-transition el-table&quot;]/div[@class=&quot;el-table__body-wrapper is-scrolling-none&quot;]/table[@class=&quot;el-table__body&quot;]/tbody[1]/tr[@class=&quot;el-table__row&quot;]/td[@class=&quot;el-table_2_column_6   el-table__cell&quot;]</value>
      <webElementGuid>ecd0d1d6-e202-4710-a108-6cc32fccab32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show-connections']/div/div/div/div[3]/table/tbody/tr/td</value>
      <webElementGuid>97dd8a36-5089-4003-a610-9275f2dfb1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authentication'])[1]/following::td[1]</value>
      <webElementGuid>73c5449b-88f1-44ad-a16e-7a9a67bfa3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connector'])[1]/following::td[1]</value>
      <webElementGuid>0cb534d9-215a-40d9-899b-0b56809b102c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otmm Monster dev'])[1]/preceding::td[5]</value>
      <webElementGuid>3a07ebce-2aca-463e-85a4-b434efec8915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>91636c49-2acd-4d04-9c61-20d3ff1ff919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Bria Connection Katalon Test' or . = 'Bria Connection Katalon Test')]</value>
      <webElementGuid>57870cdf-8837-4609-8a46-5701e62692b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
