<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-Use this link to verify your account._a50883</name>
   <tag></tag>
   <elementGuidId>6f73989f-accc-4067-9d19-76e0cd6f52af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id=':2d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>56a756d5-7a84-47f5-8fe8-71401fc79886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:2d</value>
      <webElementGuid>14fa34a6-e8ea-412d-8bcb-d737688d8bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>y2</value>
      <webElementGuid>4bbb5a50-ce94-4327-96a7-1773b9252ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> - Use this link to verify your account. OneTeg Hello baristesting, Welcome to OneTeg! Please verify your email address and set your password to activate your account on app. Click the button below to</value>
      <webElementGuid>8af9ea02-b4cc-4f44-a1ad-210ae9babbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:2d&quot;)</value>
      <webElementGuid>d5622755-a681-415c-ba63-4ee2dbbdbc8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id=':2d']</value>
      <webElementGuid>aa84a4bb-5b1c-4665-8f20-33d7fcbd5648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id=':2a']/div/div/span</value>
      <webElementGuid>9a975d69-4268-45b2-a2f8-b969816747cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify your account'])[2]/following::span[1]</value>
      <webElementGuid>c0b4b39d-052a-4ea2-a5a7-f7be0d270406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin'])[2]/following::span[3]</value>
      <webElementGuid>4d8fd43e-79ad-4452-8bac-b038432ef0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google Topluluk Eki.'])[1]/preceding::span[5]</value>
      <webElementGuid>f7cdfc61-4252-4a5e-8af4-07083711e99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Use this link to verify your account. OneTeg Hello baristesting, Welcome to OneTeg! Please verify your email address and set your password to activate your account on app. Click the button below to']/parent::*</value>
      <webElementGuid>70e83476-6dec-48f6-8561-82f506a9dd41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/span</value>
      <webElementGuid>76aad34a-351b-40ea-8085-4b7cbb174676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = ':2d' and (text() = ' - Use this link to verify your account. OneTeg Hello baristesting, Welcome to OneTeg! Please verify your email address and set your password to activate your account on app. Click the button below to' or . = ' - Use this link to verify your account. OneTeg Hello baristesting, Welcome to OneTeg! Please verify your email address and set your password to activate your account on app. Click the button below to')]</value>
      <webElementGuid>f80d452e-ab69-4607-94fd-952cf9994ad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
