<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_E-posta veya telefonE-posta adresinizi _0393df</name>
   <tag></tag>
   <elementGuidId>21922f17-211a-4288-8684-7c2f666ed172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.CxRgyd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yDmH0d']/c-wiz/div/div[2]/div/div/div/form/span/section/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97353f93-a819-4ec2-bc78-5e5cd9744519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CxRgyd</value>
      <webElementGuid>cf34a726-aea2-4b47-b7ea-0210ff56a5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>MZArnb</value>
      <webElementGuid>26ce05a8-7448-4cf7-8708-1a5f70a979a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>E-posta veya telefonE-posta adresinizi mi unuttunuz?Duyduğunuz veya gördüğünüz metni yazın</value>
      <webElementGuid>0fa1a09a-d9f1-4758-824d-a84313820d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;g98c7c&quot;]/div[@class=&quot;aDGQwe&quot;]/div[@class=&quot;eKnrVb&quot;]/div[@class=&quot;CYBold&quot;]/div[@class=&quot;j663ec&quot;]/div[@class=&quot;tCpFMc&quot;]/form[1]/span[1]/section[@class=&quot;aTzEhb&quot;]/div[@class=&quot;CxRgyd&quot;]</value>
      <webElementGuid>c4e28143-346d-45b5-a3cc-9a702d9762aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yDmH0d']/c-wiz/div/div[2]/div/div/div/form/span/section/div</value>
      <webElementGuid>7bcaa738-a30d-469a-8ca5-ca16d7ee8691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Gmail', &quot;'&quot;, 'e devam et')])[1]/following::div[5]</value>
      <webElementGuid>910f2b85-3d6f-435c-8ec4-6c1771e63621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oturum aç'])[1]/following::div[6]</value>
      <webElementGuid>1e8b7262-6ba0-465f-b1ab-2e069e510925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div</value>
      <webElementGuid>41a653f0-3360-499f-a97e-f18558c584bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'E-posta veya telefonE-posta adresinizi mi unuttunuz?Duyduğunuz veya gördüğünüz metni yazın' or . = 'E-posta veya telefonE-posta adresinizi mi unuttunuz?Duyduğunuz veya gördüğünüz metni yazın')]</value>
      <webElementGuid>982eca50-e29d-45d8-ac8f-68517fdb4747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
