<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_artlar_iNstf</name>
   <tag></tag>
   <elementGuidId>a2c693ec-a8b8-4bf4-a208-c879099dbd25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.iNstf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>04dc7d9a-573c-4180-a920-2412e5e2b695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iNstf</value>
      <webElementGuid>bb03ff1e-c331-4de8-b7c7-3eb339be806f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>46e2bebb-e65e-4794-bf39-1a2ba2fff61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;eC9N2e&quot;]/body[@class=&quot;nyoS7c UzCXuf EIlDfe&quot;]/div[@class=&quot;lJXwje S81Pef TFhTPc LZgQXe&quot;]/div[@class=&quot;iNstf&quot;]</value>
      <webElementGuid>5ca339b6-a5e1-40d3-936b-8d08d040475e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>b63400a0-ede9-4f22-ad1f-bf009d10c3f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
