<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_admin 5, Verify your account,</name>
   <tag></tag>
   <elementGuidId>e32fa11c-6dd4-403d-98ba-cff815741752</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id=':24']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tr</value>
      <webElementGuid>bb6cd1de-1792-41e7-bc0c-c90449377331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zA yO aqw</value>
      <webElementGuid>e20981aa-2701-45a7-97ee-5479daa3ae9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>ZdOxDb</value>
      <webElementGuid>7f888e7f-04f9-443c-a1ad-9fe66e7956f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>Tnvr6c:RNc9jf;PG1zDd:eyrEaf;WGbBt:UL4Ddb;nVvxM:UL4Ddb;</value>
      <webElementGuid>00915a7f-b25e-4ac5-b737-e8a34135e812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsmodel</name>
      <type>Main</type>
      <value>nXDxbd</value>
      <webElementGuid>683b0f21-36f3-46cc-b732-7bf886264f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:24</value>
      <webElementGuid>9e1ed402-be9b-49a6-a9fb-366cf837dfec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b62c6f15-e688-4533-8147-163e1e968111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>9560437c-9467-4fdf-a945-7775cb386358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>:25</value>
      <webElementGuid>24b00294-4024-48ff-9ce2-e15df55f90de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cbe15413-9415-4902-be9f-28471b2c0f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jslog</name>
      <type>Main</type>
      <value>18406; u014N:xr6bB,cOuCgd,SYhH9d; 1:WyIjdGhyZWFkLWY6MTc3MTg0NzYxMTUyMDg1OTk3MCIsMCxudWxsLG51bGwsbnVsbCwwLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsW11d</value>
      <webElementGuid>c23b6b25-1b3e-4df7-919d-b52013382160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>admin 5, Verify your account, 16:23, Use this link to verify your account. OneTeg Hello baristesting, Welcome to OneTeg! Please verify your email address and set your password to activate your account on app. Click the button below to.admin 5Verify your account - Use this link to verify your account. OneTeg Hello baristesting, Welcome to OneTeg! Please verify your email address and set your password to activate your account on app. Click the button below to 16:23</value>
      <webElementGuid>5054224d-2697-4eac-b291-771d2abd2015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:24&quot;)</value>
      <webElementGuid>6564dfc2-d8c6-402a-bcf0-e7fca06278cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//tr[@id=':24']</value>
      <webElementGuid>51147a26-3e7e-4be0-b835-0099f95f9139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id=':22']/tbody/tr</value>
      <webElementGuid>492e8d5d-528d-4a25-a1ce-a8d295352506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gelen kutusu ayarlarını'])[1]/following::tr[1]</value>
      <webElementGuid>c046504c-d06c-4491-a599-c144b70c7b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birincil sekmeniz boş.'])[1]/following::tr[1]</value>
      <webElementGuid>57086137-123e-47a5-b311-7a07e0cfdc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr</value>
      <webElementGuid>bfcd335b-402c-4c3b-b8a5-d3c340604762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tr[@id = ':24' and (text() = 'admin 5, Verify your account, 16:23, Use this link to verify your account. OneTeg Hello baristesting, Welcome to OneTeg! Please verify your email address and set your password to activate your account on app. Click the button below to.admin 5Verify your account - Use this link to verify your account. OneTeg Hello baristesting, Welcome to OneTeg! Please verify your email address and set your password to activate your account on app. Click the button below to 16:23' or . = 'admin 5, Verify your account, 16:23, Use this link to verify your account. OneTeg Hello baristesting, Welcome to OneTeg! Please verify your email address and set your password to activate your account on app. Click the button below to.admin 5Verify your account - Use this link to verify your account. OneTeg Hello baristesting, Welcome to OneTeg! Please verify your email address and set your password to activate your account on app. Click the button below to 16:23')]</value>
      <webElementGuid>fde08dcd-bf5a-4dcc-9bbb-753ea4ac3056</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
