<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Verify Account</name>
   <tag></tag>
   <elementGuidId>01f79d33-4304-465e-acff-e4e00f07c5bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div[3]/div/div/div/div/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/div/table/tbody/tr/td/table/tbody/tr/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.x_f-fallback.x_button.x_button--purple</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2595ba6b-d3f8-4125-9313-f681b03732a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://app.qa.oneteg.com/en/new-password/bcfed749-9b88-4d8c-ba12-236ee0a68dcb</value>
      <webElementGuid>1efa5cec-1dce-4fdc-acd3-38a8615659f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c2724b80-488d-4473-89fc-af5c7c553012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>fda97e58-d4fd-494b-bb19-67024e83f2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-auth</name>
      <type>Main</type>
      <value>NotApplicable</value>
      <webElementGuid>3b60969d-0a97-4f0e-a73e-4c1051005f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x_f-fallback x_button x_button--purple</value>
      <webElementGuid>7675469b-3640-47ad-8af4-1d6875f1fe4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify Account</value>
      <webElementGuid>fdbd33bd-b286-4668-ab2d-a40d38591de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReadingPaneContainerId&quot;)/div[1]/div[@class=&quot;g_zET&quot;]/div[@class=&quot;MtujV WWy1F&quot;]/div[@class=&quot;L72vd&quot;]/div[@class=&quot;Q8TCC yyYQP customScrollBar&quot;]/div[2]/div[@class=&quot;aVla3&quot;]/div[1]/div[1]/div[@class=&quot;wide-content-host&quot;]/div[@class=&quot;SlLx9 WWy1F byzS1 WWy1F&quot;]/div[@class=&quot;XbIp4 jmmB7 GNqVo yxtKT allowTextSelection&quot;]/div[1]/div[@class=&quot;rps_18d&quot;]/div[1]/div[@class=&quot;R1UVb&quot;]/table[@class=&quot;x_email-wrapper&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;x_email-content&quot;]/tbody[1]/tr[2]/td[@class=&quot;x_email-body&quot;]/table[@class=&quot;x_email-body_inner&quot;]/tbody[1]/tr[1]/td[@class=&quot;x_content-cell&quot;]/div[@class=&quot;x_f-fallback&quot;]/table[@class=&quot;x_body-action&quot;]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/a[@class=&quot;x_f-fallback x_button x_button--purple&quot;]</value>
      <webElementGuid>d1ca324d-5120-40e3-8bba-a95bd69370de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ReadingPaneContainerId']/div/div/div/div[2]/div/div[2]/div/div/div/div/div/div[3]/div/div/div/div/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td/div/table/tbody/tr/td/table/tbody/tr/td/a</value>
      <webElementGuid>1c1124ac-91e7-45e4-ac0f-e677c02415b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verify Account')]</value>
      <webElementGuid>181d57d1-babf-45eb-bb2d-d9d2f9c9f913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use this link to verify your account.'])[1]/following::a[2]</value>
      <webElementGuid>c30f06b0-2174-4ac3-809b-f8bdb2ce9c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siz'])[1]/following::a[2]</value>
      <webElementGuid>fb9c8ada-d3d2-4c02-ae0b-cae9a158c10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OneTeg Team'])[1]/preceding::a[1]</value>
      <webElementGuid>d973fe30-4044-48da-b046-885452be5970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yanıtla'])[2]/preceding::a[2]</value>
      <webElementGuid>e51be2ee-e272-4e98-88c2-531d4375e5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verify Account']/parent::*</value>
      <webElementGuid>82d74f2f-8655-48f7-87d9-14537b0d75a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://app.qa.oneteg.com/en/new-password/bcfed749-9b88-4d8c-ba12-236ee0a68dcb')]</value>
      <webElementGuid>57a3f92b-bd17-4da1-8b4b-5af1b73e9389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/table/tbody/tr/td/table/tbody/tr/td/a</value>
      <webElementGuid>0e9599a6-67bf-402b-b474-c0c4f314fb53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://app.qa.oneteg.com/en/new-password/bcfed749-9b88-4d8c-ba12-236ee0a68dcb' and (text() = 'Verify Account' or . = 'Verify Account')]</value>
      <webElementGuid>983bb22a-f8bd-49b7-9be0-940e0c0d6715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
