<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Filtre</name>
   <tag></tag>
   <elementGuidId>c8cb04fd-c85a-4805-a55e-b7512c47d9af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MainModule']/div/div/div[3]/div/div/div/div/div/div/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Xk9aW.Z9nT9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e2058be-7a4b-4a9b-adeb-1b8537561a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Xk9aW Z9nT9</value>
      <webElementGuid>03dd7aff-6f26-4326-bec0-61f2143faf75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filtre</value>
      <webElementGuid>776ba40e-9d23-4cdf-9a13-797cb3c3dce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainModule&quot;)/div[@class=&quot;SW7A6&quot;]/div[@class=&quot;LBktY&quot;]/div[@class=&quot;q9iRC css-268&quot;]/div[@class=&quot;HOVUa&quot;]/div[@class=&quot;nbmyu FkPdL czwRD LCprM&quot;]/div[@class=&quot;C1EJK LyMTI css-274&quot;]/div[@class=&quot;abF91 bkYAr rv6Vd&quot;]/div[@class=&quot;rEzfP bK01B abF91 rf8FT rqwVd&quot;]/div[@class=&quot;_EhYJ brFj8 rf8FT&quot;]/div[@class=&quot;U1j7P Z9nT9&quot;]/div[@class=&quot;ms-TooltipHost root-157&quot;]/div[@class=&quot;Xk9aW Z9nT9&quot;]</value>
      <webElementGuid>9a42fd81-553d-42f7-b37a-6af95116e35f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainModule']/div/div/div[3]/div/div/div/div/div/div/div[3]/div/div</value>
      <webElementGuid>fbfbc1a2-e7f6-4b98-94b1-bf68ef7a877a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/preceding::div[6]</value>
      <webElementGuid>a80d4444-bac3-4a9b-84e3-b8a154764110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin@oneteg.com'])[1]/preceding::div[8]</value>
      <webElementGuid>d366e1ea-0658-48e0-ac50-cd6f3470cb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filtre']/parent::*</value>
      <webElementGuid>89b7b3eb-890b-4913-b4cc-22475c3157a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[3]/div/div</value>
      <webElementGuid>efe1dd11-ad7c-4a80-af10-33f81cec7019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Filtre' or . = 'Filtre')]</value>
      <webElementGuid>06e7d1e5-7d56-4e0c-a14d-5269abfa3d8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
