<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Verify your account</name>
   <tag></tag>
   <elementGuidId>b3cb4583-783c-41be-9c8b-03c87a9b14b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AQAAAAAAAQABAAAABYdgaAAAAAA=']/div/div/div[2]/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.IjzWp.XG5Jd.gy2aJ.Ejrkd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>77828eb4-1a11-4b7e-b3b0-80ebe1653ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>IjzWp XG5Jd gy2aJ Ejrkd</value>
      <webElementGuid>3e166489-1754-42aa-9a1a-04c02d8ffc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify your account</value>
      <webElementGuid>5b268a68-fd54-417f-add3-651130eb5415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AQAAAAAAAQABAAAABYdgaAAAAAA=&quot;)/div[1]/div[@class=&quot;zKDWD YbB6r IKvQi IjQyD EhiOs JCRRb cSOXK G1NES&quot;]/div[@class=&quot;XG5Jd JtO0E&quot;]/div[@class=&quot;S2NDX&quot;]/div[@class=&quot;zht_v Q19mi&quot;]/div[@class=&quot;IjzWp XG5Jd gy2aJ Ejrkd&quot;]</value>
      <webElementGuid>7baedc7a-73df-4785-95b6-d2f8bbd8d525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AQAAAAAAAQABAAAABYdgaAAAAAA=']/div/div/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>b9bfd947-0582-4928-a361-26ce7bab6cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='admin@oneteg.com'])[1]/following::div[3]</value>
      <webElementGuid>08a88602-e3a6-4871-b02c-11b1c732ea42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/following::div[7]</value>
      <webElementGuid>3efa004a-3f78-4bdf-a26a-c533bbc6c3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[2]/preceding::div[7]</value>
      <webElementGuid>9262c37f-4644-40e8-a848-f9db933f79a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div[2]/div[2]/div</value>
      <webElementGuid>46c9f2b3-709f-4c3e-8582-41253aa5c4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Verify your account' or . = 'Verify your account')]</value>
      <webElementGuid>30bcb8d8-53f6-49bb-9349-adb647a11435</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
