<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_adminoneteg.com</name>
   <tag></tag>
   <elementGuidId>e1e91da9-d19f-4ca6-a1c9-d8a66d8d9d25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AQAAAAAAAQABAAAABYdgaAAAAAA=']/div/div/div[2]/div[2]/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span[title=&quot;admin@oneteg.com&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>471cd1a4-d75e-43e7-9894-68903c8bd109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>admin@oneteg.com</value>
      <webElementGuid>98f9f5bc-6281-43df-97b4-1e6efdcd1250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>admin@oneteg.com</value>
      <webElementGuid>0309b593-2cf1-4125-a681-5bccc1092f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AQAAAAAAAQABAAAABYdgaAAAAAA=&quot;)/div[1]/div[@class=&quot;zKDWD YbB6r IKvQi epBmH EhiOs _KLsp&quot;]/div[@class=&quot;XG5Jd JtO0E&quot;]/div[@class=&quot;S2NDX&quot;]/div[@class=&quot;KKAj0 XG5Jd&quot;]/div[@class=&quot;gMkyO gy2aJ Dc0o9 Ejrkd&quot;]/span[1]</value>
      <webElementGuid>e832d6d8-4fa3-4f41-825f-58e4f8b91851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AQAAAAAAAQABAAAABYdgaAAAAAA=']/div/div/div[2]/div[2]/div/div/span</value>
      <webElementGuid>edd94aed-4ad3-44c4-a3fa-34a66c6eec65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/following::span[1]</value>
      <webElementGuid>ddf90d22-d4e7-4344-bd00-b060b3d75b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify your account'])[1]/preceding::span[7]</value>
      <webElementGuid>ce386b75-1ce3-48b2-b297-104e978b0297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[2]/preceding::span[10]</value>
      <webElementGuid>a9c4f8d5-85eb-4783-aaf2-54e98d9dc5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='admin@oneteg.com']/parent::*</value>
      <webElementGuid>3dcc33c7-039a-499c-be9b-fc051980267b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div[2]/div/div/span</value>
      <webElementGuid>be4b82a2-04aa-4dc6-8f46-3cc50602f16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'admin@oneteg.com' and (text() = 'admin@oneteg.com' or . = 'admin@oneteg.com')]</value>
      <webElementGuid>6846bcb6-b644-4693-96c6-952fec6f5337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
